import assert from "node:assert/strict";
import { randomBytes, randomUUID } from "node:crypto";
import { Client } from "pg";
import { PrismaPg } from "@prisma/adapter-pg";
import { PrismaClient } from "../src/generated/prisma/client";
import { spawn, type ChildProcess } from "node:child_process";
import { createServer } from "node:net";
import { once } from "node:events";
import { mkdirSync, readFileSync, writeFileSync, rmSync } from "node:fs";
import { resolve } from "node:path";
import { loadDevelopmentDatabase, runPrisma } from "./lib/development-database";
import { hashPassword } from "../src/lib/auth/password";
import { ADMIN_ID } from "../src/lib/auth/policy";

async function main() {
  const connectionString = loadDevelopmentDatabase();
  const schema = `auth_verify_${randomUUID().replaceAll("-", "")}`;
  const pg = new Client({ connectionString });
  await pg.connect();
  const distDir = `.next-auth-test-${schema}`;
  let prisma: PrismaClient | undefined;
  let server: ChildProcess | undefined;
  try {
    await pg.query(`CREATE SCHEMA "${schema}"`);
    const url = new URL(connectionString); url.searchParams.set("schema", schema);
    runPrisma(["migrate", "deploy"], url.href);
    process.env.DATABASE_URL = url.href;
    prisma = new PrismaClient({ adapter: new PrismaPg({ connectionString }, { schema }), log: [] });
    (globalThis as unknown as { bookingPrisma: PrismaClient }).bookingPrisma = prisma;
    const portProbe = createServer();
    portProbe.listen(0, "127.0.0.1"); await once(portProbe, "listening");
    const port = (portProbe.address() as { port: number }).port;
    await new Promise<void>(resolve => portProbe.close(() => resolve()));
    const origin = `http://127.0.0.1:${port}`;
    process.env.AUTH_URL = origin;
    process.env.AUTH_SECRET = randomBytes(32).toString("hex");
    process.env.AUTH_RATE_LIMIT_SECRET = randomBytes(32).toString("hex");
    process.env.MAIL_PAYLOAD_KEY = randomBytes(32).toString("base64");
    process.env.MAIL_TEST_DISABLE_IMMEDIATE = "1";
    process.env.RESEND_FROM = "mail@example.test";
    process.env.ADMIN_EMAIL = "admin@example.test";
    process.env.ADMIN_PASSWORD = randomBytes(24).toString("base64url");
    process.env.ADMIN_AUTH_VERSION = "1";
    await prisma.adminAccount.create({ data: { id: ADMIN_ID, displayName: "Test administrator" } });
    const password = randomBytes(24).toString("base64url");
    const staff = await prisma.staffAccount.create({ data: { email: "staff@example.test", emailKey: "staff@example.test", displayName: "Test staff", passwordHash: await hashPassword(password) } });
    mkdirSync(distDir);
    const testTsconfig = JSON.parse(readFileSync("tsconfig.json", "utf8"));
    testTsconfig.include = [resolve("src/**/*.ts"), resolve("src/**/*.tsx"), resolve("next-env.d.ts")];
    testTsconfig.compilerOptions.baseUrl = process.cwd();
    testTsconfig.compilerOptions.paths = { "@/*": ["./src/*"] };
    writeFileSync(`${distDir}/tsconfig.json`, JSON.stringify(testTsconfig));
    server = spawn(process.execPath, ["node_modules/next/dist/bin/next", "dev", "--webpack", "-p", String(port), "-H", "127.0.0.1"], {
      env: { ...process.env, NODE_OPTIONS: "", DATABASE_URL: url.href, DIRECT_URL: url.href, NEXT_DIST_DIR: distDir, AUTH_TEST_TSCONFIG: `${distDir}/tsconfig.json` }, stdio: ["ignore", "pipe", "pipe"],
    });
    let serverOutput = "";
    server.stdout?.on("data", chunk => { serverOutput = (serverOutput + String(chunk)).slice(-8000); });
    server.stderr?.on("data", chunk => { serverOutput = (serverOutput + String(chunk)).slice(-8000); });
    let ready = false;
    for (let i = 0; i < 90; i++) {
      try { if ((await fetch(`${origin}/api/auth/csrf`)).ok) { ready = true; break; } } catch {}
      if (server.exitCode !== null) break;
      await new Promise(resolve => setTimeout(resolve, 500));
    }
    if (!ready) console.error(serverOutput.replaceAll(process.env.ADMIN_PASSWORD!, "[redacted]").split("\n").filter(line => !line.includes("GET /api/auth/")).join("\n"));
    assert(ready, "Test server did not become ready.");
    const { resolveSession } = await import("../src/lib/auth/session");
    const { consumeLoginAttempt, LoginRateLimited } = await import("../src/lib/auth/rate-limit");
    const { getToken, encode } = await import("next-auth/jwt");
    const jar = new Map<string, string>();
    const cookie = () => [...jar].map(([k,v]) => `${k}=${v}`).join("; ");
    async function call(path: string, body?: Record<string,string>, customOrigin = origin, customCookie = cookie()) {
      const response = await fetch(`${origin}/api/auth/${path}`, { method: body ? "POST" : "GET", headers: { cookie: customCookie, origin: customOrigin, ...(body ? { "content-type": "application/x-www-form-urlencoded", "x-auth-return-redirect": "1" } : {}) }, ...(body ? { body: new URLSearchParams(body) } : {}) });
      for (const raw of response.headers.getSetCookie()) {
        const [name, ...parts] = raw.split(";")[0].split("=");
        const value = parts.join("=");
        if (value) jar.set(name, value); else jar.delete(name);
      }
      return response;
    }
    async function login(role: "admin" | "staff", email: string, secret: string) {
      const csrf = await (await call("csrf")).json();
      return call(`callback/${role}`, { email, password: secret, csrfToken: csrf.csrfToken, callbackUrl: "/manage" });
    }
    async function resetAttempts() { await prisma!.rateLimitBucket.deleteMany(); }
    const protectedGet = (path: string, sessionCookie = cookie()) => fetch(`${origin}${path}`, {
      headers: { cookie: sessionCookie }, redirect: "manual",
    });
    const mutation = (path: string, body: Record<string, unknown>, sessionCookie = cookie(), requestOrigin = origin) => fetch(`${origin}${path}`, {
      method: "POST", headers: { cookie: sessionCookie, origin: requestOrigin, "content-type": "application/json" }, body: JSON.stringify(body),
    });
    const patch = (path: string, body: Record<string, unknown>, sessionCookie = cookie(), requestOrigin = origin) => fetch(`${origin}${path}`, {
      method: "PATCH", headers: { cookie: sessionCookie, origin: requestOrigin, "content-type": "application/json" }, body: JSON.stringify(body),
    });
    const previewSchedule = async (body: Record<string, unknown>, sessionCookie = activeAdminCookie) => {
      const response = await mutation("/api/manage/schedules/preview", body, sessionCookie);
      assert.equal(response.status, 200);
      return response.json() as Promise<{ reviewToken: string; mode: string; impact: { reservationId: string; before: string | null; after: string | null }[] }>;
    };
    const saveSchedule = async (body: Record<string, unknown>, sessionCookie = activeAdminCookie) => mutation("/api/manage/schedules", { ...body, reviewToken: (await previewSchedule(body, sessionCookie)).reviewToken }, sessionCookie);
    const previewResourceDisable = async (path: string, updatedAt: string) => {
      const response = await patch(path, { operation: "preview-disable", updatedAt }, activeAdminCookie);
      assert.equal(response.status, 200);
      return response.json() as Promise<{ reviewToken: string; affected: { reservationId: string }[] }>;
    };
    assert.equal(await (await call("session")).json(), null);
    assert.equal((await fetch(`${origin}/api/manage/staff`)).status, 401);
    for (const [path, destination] of [["/manage", "/staff/login"], ["/manage/staff", "/admin/login"]]) {
      const response = await protectedGet(path);
      assert.equal(response.status, 307);
      assert.equal(new URL(response.headers.get("location")!, origin).pathname, destination);
      assert.doesNotMatch(await response.text(), /staff@example\.test/);
    }
    assert.equal((await call("callback/admin", { email: "x", password: "x" }, "https://evil.test")).status, 403);
    assert.equal((await call("callback/admin", { email: "admin@example.test", password: process.env.ADMIN_PASSWORD })).status, 403);
    assert.equal(await prisma.appSession.count(), 0);
    assert.match((await (await login("admin", "admin@example.test", "wrong-password-value")).json()).url, /CredentialsSignin/);
    assert.match((await (await login("admin", "staff@example.test", password)).json()).url, /CredentialsSignin/);
    await resetAttempts();
    assert.equal((await login("admin", " ADMIN@example.test ", process.env.ADMIN_PASSWORD)).status, 200);
    const adminSession = await (await call("session")).json();
    assert.equal(adminSession.user.role, "ADMIN");
    assert.deepEqual(Object.keys(adminSession.user).sort(), ["id", "role"]);
    const adminRoster = await fetch(`${origin}/api/manage/staff`, { headers: { cookie: cookie() } });
    assert.equal(adminRoster.status, 200);
    assert.equal(adminRoster.headers.get("cache-control"), "no-store");
    assert.deepEqual((await adminRoster.json()).staff.map((person: { id: string }) => person.id), [staff.id]);
    assert.match(await (await fetch(`${origin}/manage/staff`, { headers: { cookie: cookie() } })).text(), /staff@example\.test/);
    const savedCookie = cookie();
    const token = await getToken({ req: new Request(origin, { headers: { cookie: savedCookie } }), secret: process.env.AUTH_SECRET, secureCookie: false });
    assert(token);
    const absoluteExpiry = token.absoluteExpiry;
    await call("session"); // Auth.js may refresh the JWT cookie.
    const refreshed = await getToken({ req: new Request(origin, { headers: { cookie: cookie() } }), secret: process.env.AUTH_SECRET, secureCookie: false });
    assert.equal(refreshed?.absoluteExpiry, absoluteExpiry);
    assert.equal(await resolveSession(token, new Date(Number(token.absoluteExpiry) - 1)) !== null, true);
    assert.equal(await resolveSession(token, new Date(Number(token.absoluteExpiry))), null);
    const expiredAt = new Date(Date.now() - 1000);
    const expiredRow = await prisma.appSession.create({ data: {
      principalType: "ADMIN", adminId: ADMIN_ID, authVersion: 1,
      createdAt: new Date(expiredAt.getTime() - 8 * 60 * 60_000), expiresAt: expiredAt,
    } });
    const expiredJwt = await encode({
      token: { sid: expiredRow.id, principalId: ADMIN_ID, role: "ADMIN", authVersion: 1, absoluteExpiry: expiredAt.getTime() },
      secret: process.env.AUTH_SECRET, salt: "authjs.session-token", maxAge: 8 * 60 * 60,
    });
    const expiredCookie = `authjs.session-token=${expiredJwt}`;
    assert.equal(await resolveSession({ sid: expiredRow.id, principalId: ADMIN_ID, role: "ADMIN", authVersion: 1, absoluteExpiry: expiredAt.getTime() }), null);
    assert.equal((await protectedGet("/api/manage/staff", expiredCookie)).status, 401);
    assert.equal(await (await protectedGet("/api/auth/session", expiredCookie)).json(), null);
    const expiredPage = await protectedGet("/manage/staff", expiredCookie);
    assert.equal(expiredPage.status, 307);
    assert.equal(new URL(expiredPage.headers.get("location")!, origin).pathname, "/admin/login");
    assert.doesNotMatch(await expiredPage.text(), /staff@example\.test/);
    const expiredOverview = await protectedGet("/manage", expiredCookie);
    assert.equal(expiredOverview.status, 307);
    assert.equal(new URL(expiredOverview.headers.get("location")!, origin).pathname, "/staff/login");
    assert.match((await (await login("staff", "staff@example.test", password)).json()).url, /already_signed_in/);
    const csrf = await (await call("csrf")).json();
    assert.equal((await call("signout", { csrfToken: csrf.csrfToken })).status, 200);
    assert.equal(await resolveSession(token), null);
    assert.equal(await (await call("session", undefined, origin, savedCookie)).json(), null);
    assert.equal((await protectedGet("/api/manage/staff", savedCookie)).status, 401);
    await resetAttempts();
    await login("admin", "admin@example.test", process.env.ADMIN_PASSWORD);
    const activeAdminCookie = cookie();
    const currentAdminToken = await getToken({ req: new Request(origin, { headers: { cookie: cookie() } }), secret: process.env.AUTH_SECRET, secureCookie: false });
    process.env.ADMIN_AUTH_VERSION = "2";
    assert.equal(await resolveSession(currentAdminToken), null);
    process.env.ADMIN_AUTH_VERSION = "1";
    await prisma.adminAccount.update({ where: { id: ADMIN_ID }, data: { isActive: false } });
    assert.equal(await (await call("session")).json(), null);
    await login("staff", "staff@example.test", password);
    assert.equal((await (await call("session")).json()).user.role, "STAFF");
    assert.equal(await prisma.staffPermission.count(), 0);
    assert.equal((await fetch(`${origin}/api/manage/staff`, { headers: { cookie: cookie() } })).status, 403);
    const forbiddenPage = await protectedGet("/manage/staff");
    assert.match(await forbiddenPage.text(), /スタッフ一覧を閲覧する権限がありません/);
    assert.doesNotMatch(await (await protectedGet("/manage/staff")).text(), /staff@example\.test/);
    assert.match(await (await fetch(`${origin}/manage`, { headers: { cookie: cookie() } })).text(), /現在は閲覧のみ可能です/);
    await prisma.adminAccount.update({ where: { id: ADMIN_ID }, data: { isActive: true } });
    const staffPath = `/api/manage/staff/${staff.id}/permissions`;
    assert.match(await (await protectedGet(`/manage/staff/${staff.id}`, activeAdminCookie)).text(), /権限の付与・解除/);
    assert.doesNotMatch(await (await protectedGet(`/manage/staff/${staff.id}`)).text(), /staff@example\.test/);
    assert.equal((await mutation("/api/manage/staff", { displayName: "Invalid", email: "invalid@example.test", password: password }, cookie(), "https://evil.test")).status, 403);
    assert.equal((await mutation(staffPath, { permission: "STAFF_CREATE", enabled: true }, activeAdminCookie, "https://evil.test")).status, 403);
    assert.equal((await mutation(staffPath, { permission: "STAFF_CREATE", enabled: true })).status, 403);
    assert.equal((await mutation(staffPath, { permission: "STAFF_PERMISSION_MANAGE", enabled: true }, activeAdminCookie)).status, 400);
    assert.equal((await mutation(staffPath, { permission: "STAFF_CREATE", enabled: true }, activeAdminCookie)).status, 200);
    assert.equal((await mutation(staffPath, { permission: "STAFF_CREATE", enabled: true }, activeAdminCookie)).status, 200);
    assert.equal(await prisma.auditLog.count({ where: { action: "STAFF_PERMISSION_GRANTED" } }), 1);
    assert.match(await (await protectedGet("/manage", cookie())).text(), /更新操作の権限が1件/);
    assert.equal((await protectedGet("/api/manage/staff")).status, 403);
    assert.equal((await mutation(staffPath, { permission: "RESERVATION_CREATE", enabled: true })).status, 403);
    const createdResponse = await mutation("/api/manage/staff", { displayName: "Created staff", email: " CREATED@example.test ", password });
    assert.equal(createdResponse.status, 201);
    const created = await createdResponse.json() as { id: string };
    assert.equal((await prisma.staffAccount.findUniqueOrThrow({ where: { id: created.id } })).emailKey, "created@example.test");
    assert.equal(await prisma.staffPermission.count({ where: { staffId: created.id } }), 0);
    const newStaffExpiry = new Date(Date.now() + 8 * 60 * 60_000);
    const newStaffSession = await prisma.appSession.create({ data: { principalType: "STAFF", staffId: created.id, authVersion: 1, expiresAt: newStaffExpiry } });
    const newStaffJwt = await encode({ token: { sid: newStaffSession.id, principalId: created.id, role: "STAFF", authVersion: 1, absoluteExpiry: newStaffExpiry.getTime() }, secret: process.env.AUTH_SECRET, salt: "authjs.session-token", maxAge: 8 * 60 * 60 });
    const newStaffCookie = `authjs.session-token=${newStaffJwt}`;
    assert.match(await (await protectedGet("/manage", newStaffCookie)).text(), /現在は閲覧のみ可能です/);
    assert.equal((await mutation("/api/manage/staff", { displayName: "No grant", email: "no-grant@example.test", password }, newStaffCookie)).status, 403);
    assert.equal((await mutation("/api/manage/staff", { displayName: "Again", email: "created@example.test", password })).status, 409);
    assert.equal((await mutation(staffPath, { permission: "STAFF_CREATE", enabled: false }, activeAdminCookie)).status, 200);
    assert.equal((await mutation("/api/manage/staff", { displayName: "Denied", email: "denied@example.test", password })).status, 403);
    assert.equal(await prisma.staffAccount.count({ where: { emailKey: "denied@example.test" } }), 0);
    assert.match(await (await protectedGet("/manage")).text(), /現在は閲覧のみ可能です/);
    assert.equal(await prisma.auditLog.count({ where: { action: "STAFF_PERMISSION_REVOKED" } }), 1);
    assert.equal((await mutation("/api/manage/staff", { displayName: "Admin created", email: "admin-created@example.test", password }, activeAdminCookie)).status, 201);
    await prisma.staffPermission.create({ data: { staffId: staff.id, permission: "RESERVATION_CANCEL", grantedByAdminId: ADMIN_ID } });
    assert.match(await (await fetch(`${origin}/manage`, { headers: { cookie: cookie() } })).text(), /更新操作の権限が1件/);
    assert.equal((await fetch(`${origin}/api/manage/staff`, { headers: { cookie: cookie() } })).status, 403);
    await prisma.staffPermission.delete({ where: { staffId_permission: { staffId: staff.id, permission: "RESERVATION_CANCEL" } } });
    assert.match(await (await fetch(`${origin}/manage`, { headers: { cookie: cookie() } })).text(), /現在は閲覧のみ可能です/);
    const treatmentsPath = "/api/manage/catalog/treatments";
    const optionsPath = "/api/manage/catalog/options";
    const catalogPage = await protectedGet("/manage/catalog");
    assert.equal(catalogPage.status, 200);
    assert.match(await catalogPage.text(), /メニュー・オプション管理/);
    assert.equal((await protectedGet("/manage/catalog", "")).status, 307);
    assert.equal((await protectedGet(treatmentsPath, "")).status, 401);
    assert.equal((await protectedGet(treatmentsPath)).status, 200);
    assert.equal((await mutation(treatmentsPath, { name: "Denied", durationMinutes: "60", priceYen: "1000" })).status, 403);
    assert.equal((await mutation(treatmentsPath, { name: "Denied", durationMinutes: "60", priceYen: "1000" }, activeAdminCookie, "https://evil.test")).status, 403);
    for (const invalid of [
      { name: "Zero", durationMinutes: "0", priceYen: "1000" },
      { name: "Decimal", durationMinutes: "1.5", priceYen: "1000" },
      { name: "Comma", durationMinutes: "60", priceYen: "1,000" },
      { name: "Exp", durationMinutes: "1e3", priceYen: "1000" },
      { name: "Excess", durationMinutes: "1381", priceYen: "1000" },
      { name: "Price", durationMinutes: "60", priceYen: "1000001" },
      { name: "Bad\nName", durationMinutes: "60", priceYen: "1000" },
    ]) assert.equal((await mutation(treatmentsPath, invalid, activeAdminCookie)).status, 400);
    const treatmentResponse = await mutation(treatmentsPath, { name: " Test treatment ", durationMinutes: "1380", priceYen: "1000000" }, activeAdminCookie);
    assert.equal(treatmentResponse.status, 201);
    const treatment = await treatmentResponse.json() as { id: string; updatedAt: string };
    assert.equal((await prisma.treatment.findUniqueOrThrow({ where: { id: treatment.id } })).name, "Test treatment");
    const optionResponse = await mutation(optionsPath, { name: " Zero option ", durationMinutes: "0", priceYen: "0" }, activeAdminCookie);
    assert.equal(optionResponse.status, 201);
    const option = await optionResponse.json() as { id: string; updatedAt: string };
    assert.equal((await prisma.option.findUniqueOrThrow({ where: { id: option.id } })).durationMinutes, 0);
    const treatmentItemPath = `${treatmentsPath}/${treatment.id}`;
    const optionItemPath = `${optionsPath}/${option.id}`;
    const optionUpdatedResponse = await patch(optionItemPath, { operation: "update", updatedAt: option.updatedAt, name: "Edited option", durationMinutes: "0", priceYen: "500" }, activeAdminCookie);
    assert.equal(optionUpdatedResponse.status, 200);
    const optionUpdated = await optionUpdatedResponse.json() as { updatedAt: string };
    assert.equal((await patch(treatmentItemPath, { operation: "update", updatedAt: treatment.updatedAt, name: "Changed", durationMinutes: "60", priceYen: "0" })).status, 403);
    assert.equal((await mutation(staffPath, { permission: "TREATMENT_UPDATE", enabled: true }, activeAdminCookie)).status, 200);
    assert.equal((await mutation(treatmentsPath, { name: "No create", durationMinutes: "60", priceYen: "0" })).status, 403);
    const updatedResponse = await patch(treatmentItemPath, { operation: "update", updatedAt: treatment.updatedAt, name: " Changed ", durationMinutes: "60", priceYen: "0" });
    assert.equal(updatedResponse.status, 200);
    const updated = await updatedResponse.json() as { updatedAt: string };
    assert.equal((await patch(treatmentItemPath, { operation: "update", updatedAt: treatment.updatedAt, name: "Stale", durationMinutes: "90", priceYen: "1" })).status, 409);
    assert.equal((await patch(treatmentItemPath, { operation: "disable", updatedAt: updated.updatedAt })).status, 403);
    assert.equal((await mutation(staffPath, { permission: "TREATMENT_UPDATE", enabled: false }, activeAdminCookie)).status, 200);
    assert.equal((await patch(treatmentItemPath, { operation: "update", updatedAt: updated.updatedAt, name: "Denied again", durationMinutes: "90", priceYen: "1" })).status, 403);
    assert.equal((await mutation(staffPath, { permission: "OPTION_DISABLE", enabled: true }, activeAdminCookie)).status, 200);
    assert.equal((await patch(optionItemPath, { operation: "disable", updatedAt: optionUpdated.updatedAt })).status, 200);
    assert.equal((await prisma.option.findUniqueOrThrow({ where: { id: option.id } })).isActive, false);
    assert.equal((await patch(optionItemPath, { operation: "disable", updatedAt: option.updatedAt })).status, 409);
    assert.equal((await mutation(staffPath, { permission: "OPTION_DISABLE", enabled: false }, activeAdminCookie)).status, 200);
    const currentTreatment = await prisma.treatment.findUniqueOrThrow({ where: { id: treatment.id } });
    assert.equal((await patch(treatmentItemPath, { operation: "disable", updatedAt: currentTreatment.updatedAt.toISOString() }, activeAdminCookie)).status, 200);
    assert.equal((await prisma.treatment.findUniqueOrThrow({ where: { id: treatment.id } })).isActive, false);
    assert.equal(await prisma.auditLog.count({ where: { action: "TREATMENT_CREATED" } }), 1);
    assert.equal(await prisma.auditLog.count({ where: { action: "TREATMENT_UPDATED" } }), 1);
    assert.equal(await prisma.auditLog.count({ where: { action: "TREATMENT_DISABLED" } }), 1);
    assert.equal(await prisma.auditLog.count({ where: { action: "OPTION_CREATED" } }), 1);
    assert.equal(await prisma.auditLog.count({ where: { action: "OPTION_UPDATED" } }), 1);
    assert.equal(await prisma.auditLog.count({ where: { action: "OPTION_DISABLED" } }), 1);
    const roomsPath = "/api/manage/resources/rooms";
    const therapistsPath = "/api/manage/resources/therapists";
    const resourcesPage = await protectedGet("/manage/resources");
    assert.equal(resourcesPage.status, 200);
    assert.match(await resourcesPage.text(), /部屋・施術者管理/);
    assert.equal((await protectedGet("/manage/resources", "")).status, 307);
    assert.equal((await protectedGet(roomsPath, "")).status, 401);
    assert.equal((await mutation(roomsPath, { name: "Denied" })).status, 403);
    assert.equal((await mutation(roomsPath, { name: "Denied" }, activeAdminCookie, "https://evil.test")).status, 403);
    for (const name of ["", "   ", "Bad\nName", "x".repeat(101)]) assert.equal((await mutation(roomsPath, { name }, activeAdminCookie)).status, 400);
    const roomResponse = await mutation(roomsPath, { name: " Room A " }, activeAdminCookie);
    assert.equal(roomResponse.status, 201);
    const room = await roomResponse.json() as { id: string; updatedAt: string };
    assert.equal((await prisma.room.findUniqueOrThrow({ where: { id: room.id } })).name, "Room A");
    const spareRoomResponse = await mutation(roomsPath, { name: "Room B" }, activeAdminCookie);
    assert.equal(spareRoomResponse.status, 201);
    const spareRoom = await spareRoomResponse.json() as { id: string; updatedAt: string };
    const therapistResponse = await mutation(therapistsPath, { name: "Therapist A" }, activeAdminCookie);
    assert.equal(therapistResponse.status, 201);
    const therapist = await therapistResponse.json() as { id: string; updatedAt: string };
    assert.equal(await prisma.room.count({ where: { isActive: true } }), 2);
    assert.equal(await prisma.therapist.count({ where: { isActive: true } }), 1);
    const roomItemPath = `${roomsPath}/${room.id}`;
    const spareRoomPath = `${roomsPath}/${spareRoom.id}`;
    const therapistItemPath = `${therapistsPath}/${therapist.id}`;
    assert.equal((await patch(roomItemPath, { operation: "update", updatedAt: room.updatedAt, name: "No permission" })).status, 403);
    assert.equal((await mutation(staffPath, { permission: "ROOM_UPDATE", enabled: true }, activeAdminCookie)).status, 200);
    assert.equal((await mutation(roomsPath, { name: "Still denied" })).status, 403);
    const roomUpdatedResponse = await patch(roomItemPath, { operation: "update", updatedAt: room.updatedAt, name: " Updated Room " });
    assert.equal(roomUpdatedResponse.status, 200);
    const roomUpdated = await roomUpdatedResponse.json() as { updatedAt: string };
    assert.equal((await patch(roomItemPath, { operation: "update", updatedAt: room.updatedAt, name: "Stale room" })).status, 409);
    assert.equal((await patch(roomItemPath, { operation: "disable", updatedAt: roomUpdated.updatedAt })).status, 403);
    assert.equal((await mutation(staffPath, { permission: "ROOM_UPDATE", enabled: false }, activeAdminCookie)).status, 200);
    assert.equal((await patch(roomItemPath, { operation: "update", updatedAt: roomUpdated.updatedAt, name: "Revoked" })).status, 403);
    const therapistUpdatedResponse = await patch(therapistItemPath, { operation: "update", updatedAt: therapist.updatedAt, name: "Updated therapist" }, activeAdminCookie);
    assert.equal(therapistUpdatedResponse.status, 200);
    const therapistUpdated = await therapistUpdatedResponse.json() as { updatedAt: string };
    const member = await prisma.member.create({ data: { email: "booked@example.test", emailKey: "booked@example.test", lastName: "Test", firstName: "Member", lastNameKey: "test", firstNameKey: "member", phoneNumber: "09012345678", postalCode: "1234567", ageBand: 30, passwordHash: await hashPassword(password), status: "ACTIVE", emailVerifiedAt: new Date(), firstActivatedAt: new Date() } });
    const activeTreatment = await prisma.treatment.create({ data: { name: "Booked treatment", durationMinutes: 60, priceYen: 1000 } });
    const startsAt = new Date(Date.now() + 30 * 24 * 60 * 60_000);
    startsAt.setUTCHours(1, 0, 0, 0);
    const endsAt = new Date(startsAt.getTime() + 60 * 60_000);
    const reservation = await prisma.reservation.create({ data: { memberId: member.id, treatmentId: activeTreatment.id, roomId: room.id, therapistId: therapist.id, memberLastNameSnapshot: "Test", memberFirstNameSnapshot: "Member", memberEmailSnapshot: member.email, memberPhoneNumberSnapshot: member.phoneNumber, treatmentNameSnapshot: activeTreatment.name, treatmentDurationMinutesSnapshot: 60, treatmentPriceYenSnapshot: 1000, roomNameSnapshot: "Updated Room", therapistNameSnapshot: "Updated therapist", businessDate: new Date(`${startsAt.toISOString().slice(0, 10)}T00:00:00.000Z`), startsAt, treatmentEndsAt: endsAt, occupiesUntil: endsAt, totalDurationMinutes: 60, totalPriceYen: 1000, slotCount: 1 } });
    await prisma.reservationSlot.create({ data: { reservationId: reservation.id, roomId: room.id, therapistId: therapist.id, slotStartsAt: startsAt } });
    const blockedRoom = await patch(roomItemPath, { operation: "disable", updatedAt: roomUpdated.updatedAt }, activeAdminCookie);
    assert.equal(blockedRoom.status, 409);
    assert.equal((await blockedRoom.json()).error, "ReviewRequired");
    assert.equal((await prisma.room.findUniqueOrThrow({ where: { id: room.id } })).isActive, true);
    const roomReview = await previewResourceDisable(roomItemPath, roomUpdated.updatedAt);
    assert.deepEqual(roomReview.affected.map((row) => row.reservationId), [reservation.id]);
    assert.equal((await patch(roomItemPath, { operation: "disable", updatedAt: roomUpdated.updatedAt, reviewToken: roomReview.reviewToken }, activeAdminCookie)).status, 200);
    assert.equal(await prisma.reservationSlot.count({ where: { reservationId: reservation.id } }), 1);
    assert.equal(await prisma.reservationChangeNotice.count({ where: { reservationId: reservation.id, reason: "RESOURCE_UNAVAILABLE" } }), 1);
    const notice = await prisma.reservationChangeNotice.findFirstOrThrow({ where: { reservationId: reservation.id, reason: "RESOURCE_UNAVAILABLE" } });
    const noticePath = `/api/manage/adjustments/${notice.id}/send`;
    assert.equal(await prisma.emailDelivery.count({ where: { noticeId: notice.id } }), 0);
    assert.equal((await mutation(noticePath, { expectedVersion: notice.version, confirmed: true }, "")).status, 401);
    assert.equal((await mutation(noticePath, { expectedVersion: notice.version, confirmed: true })).status, 403);
    const duplicateSends = await Promise.all([mutation(noticePath, { expectedVersion: notice.version, confirmed: true }, activeAdminCookie), mutation(noticePath, { expectedVersion: notice.version, confirmed: true }, activeAdminCookie)]);
    assert.deepEqual(duplicateSends.map((response) => response.status), [200, 200]);
    assert.equal(await prisma.emailDelivery.count({ where: { noticeId: notice.id } }), 1);
    assert.equal(await prisma.auditLog.count({ where: { action: "CHANGE_NOTICE_SEND_CONFIRMED", targetId: notice.id } }), 1);
    const { runMailBatch } = await import("../src/lib/mail/worker");
    const sentNotices: string[] = [];
    const sent = await runMailBatch(async (payload, key) => { assert.match(payload.text, /店舗までご連絡/); sentNotices.push(key); return { kind: "ACCEPTED" }; }, 1, prisma);
    assert.equal(sent.attempted, 1);
    assert.equal(sentNotices.length, 1);
    assert.equal((await prisma.emailDelivery.findFirstOrThrow({ where: { noticeId: notice.id } })).status, "ACCEPTED");
    const spareReview = await previewResourceDisable(spareRoomPath, spareRoom.updatedAt);
    assert.equal(spareReview.affected.length, 0);
    assert.equal((await patch(spareRoomPath, { operation: "disable", updatedAt: spareRoom.updatedAt, reviewToken: spareReview.reviewToken }, activeAdminCookie)).status, 200);
    assert.equal(await prisma.room.count({ where: { isActive: true } }), 0);
    const therapistReview = await previewResourceDisable(therapistItemPath, therapistUpdated.updatedAt);
    assert.deepEqual(therapistReview.affected.map((row) => row.reservationId), [reservation.id]);
    assert.equal((await patch(therapistItemPath, { operation: "disable", updatedAt: therapistUpdated.updatedAt, reviewToken: therapistReview.reviewToken }, activeAdminCookie)).status, 200);
    await prisma.reservation.update({ where: { id: reservation.id }, data: { status: "IN_PROGRESS", actualStartedAt: new Date() } });
    assert.equal(await prisma.reservationChangeNotice.count({ where: { reservationId: reservation.id } }), 2);
    assert.equal(await prisma.reservationSlot.count({ where: { reservationId: reservation.id } }), 1);
    assert.equal(await prisma.room.count({ where: { isActive: true } }), 0);
    assert.equal(await prisma.therapist.count({ where: { isActive: true } }), 0);
    assert.equal(await prisma.auditLog.count({ where: { action: "ROOM_CREATED" } }), 2);
    assert.equal(await prisma.auditLog.count({ where: { action: "ROOM_UPDATED" } }), 1);
    assert.equal(await prisma.auditLog.count({ where: { action: "ROOM_DISABLED" } }), 2);
    assert.equal(await prisma.auditLog.count({ where: { action: "THERAPIST_CREATED" } }), 1);
    assert.equal(await prisma.auditLog.count({ where: { action: "THERAPIST_UPDATED" } }), 1);
    assert.equal(await prisma.auditLog.count({ where: { action: "THERAPIST_DISABLED" } }), 1);
    const schedulePath = "/api/manage/schedules";
    const schedulePage = await protectedGet("/manage/schedules");
    assert.equal(schedulePage.status, 200);
    assert.match(await schedulePage.text(), /営業日・営業時間・休憩設定/);
    assert.equal((await protectedGet("/manage/schedules", "")).status, 307);
    assert.equal((await protectedGet(schedulePath, "")).status, 401);
    const scheduleDate = new Date(Date.now() + 45 * 24 * 60 * 60_000);
    scheduleDate.setUTCHours(0, 0, 0, 0);
    const effectiveDate = scheduleDate.toISOString().slice(0, 10);
    const nearDate = new Date(Date.now() + 10 * 24 * 60 * 60_000).toISOString().slice(0, 10);
    const weeklyDays = Array.from({ length: 7 }, (_, weekday) => ({ weekday, isOpen: weekday !== 0, opensAt: weekday === 0 ? null : "09:00", closesAt: "18:00" }));
    const scheduleBaseVersion = (await prisma.storeSettingState.findUniqueOrThrow({ where: { id: 1 } })).version;
    const weeklyBody = { kind: "BUSINESS_WEEKLY", effectiveDate, expectedVersion: scheduleBaseVersion, reason: "Test weekly setting", days: weeklyDays };
    assert.equal((await mutation(schedulePath, weeklyBody)).status, 403);
    assert.equal((await mutation(schedulePath, weeklyBody, activeAdminCookie, "https://evil.test")).status, 403);
    assert.equal((await previewSchedule({ ...weeklyBody, effectiveDate: nearDate })).mode, "NEAR_TERM");
    assert.equal((await mutation(schedulePath, { ...weeklyBody, days: weeklyDays.slice(1) }, activeAdminCookie)).status, 400);
    assert.equal((await mutation(schedulePath, { ...weeklyBody, days: weeklyDays.map((day) => ({ ...day, closesAt: "18:30" })) }, activeAdminCookie)).status, 400);
    assert.equal((await (await mutation(schedulePath, weeklyBody, activeAdminCookie)).json()).error, "ReviewRequired");
    const weeklyResponse = await saveSchedule(weeklyBody);
    assert.equal(weeklyResponse.status, 200);
    const weeklySaved = await weeklyResponse.json() as { planId: string; revision: number; version: number };
    assert.equal(weeklySaved.revision, 1);
    assert.equal(weeklySaved.version, scheduleBaseVersion + 1);
    const { getEffectiveBusinessDay, getEffectiveTherapistBreak, getAssignableTherapistsForDate } = await import("../src/lib/schedules/effective");
    assert.equal((await getEffectiveBusinessDay(prisma, effectiveDate))?.closesAt.getUTCHours(), 18);
    assert.equal((await mutation(schedulePath, weeklyBody, activeAdminCookie)).status, 409);
    assert.equal((await (await mutation(schedulePath, { ...weeklyBody, expectedVersion: scheduleBaseVersion + 1 }, activeAdminCookie)).json()).error, "ExistingPlanReviewPending");
    assert.equal((await mutation(staffPath, { permission: "BUSINESS_SETTING_MANAGE", enabled: true }, activeAdminCookie)).status, 200);
    const revisedDays = weeklyDays.map((day) => ({ ...day, closesAt: "17:00" }));
    const reviseResponse = await saveSchedule({ ...weeklyBody, expectedVersion: scheduleBaseVersion + 1, expectedRevision: 1, reason: "Revise weekly", days: revisedDays }, cookie());
    assert.equal(reviseResponse.status, 200);
    const revised = await reviseResponse.json() as { planId: string; revision: number; version: number };
    assert.equal(revised.planId, weeklySaved.planId);
    assert.equal(revised.revision, 2);
    assert.equal(revised.version, scheduleBaseVersion + 2);
    assert.equal((await getEffectiveBusinessDay(prisma, effectiveDate))?.closesAt.getUTCHours(), 17);
    assert.equal((await mutation(staffPath, { permission: "BUSINESS_SETTING_MANAGE", enabled: false }, activeAdminCookie)).status, 200);
    assert.equal((await mutation(schedulePath, { ...weeklyBody, expectedVersion: scheduleBaseVersion + 2 })).status, 403);
    const scheduledTherapist = await prisma.therapist.create({ data: { name: "Break test therapist" } });
    const breaks = Array.from({ length: 7 }, (_, weekday) => ({ weekday, startsAt: weekday === 0 || weekday === 2 ? null : "12:00", endsAt: weekday === 0 || weekday === 2 ? null : "13:00" }));
    const breakBody = { kind: "THERAPIST_BREAK", effectiveDate, expectedVersion: scheduleBaseVersion + 2, reason: "Add weekly breaks", therapistId: scheduledTherapist.id, breaks };
    assert.equal((await mutation(schedulePath, breakBody)).status, 403);
    assert.equal((await mutation(schedulePath, { ...breakBody, breaks: breaks.map((day) => ({ ...day, startsAt: day.weekday === 1 ? "17:00" : day.startsAt, endsAt: day.weekday === 1 ? "18:00" : day.endsAt })) }, activeAdminCookie)).status, 400);
    assert.equal((await mutation(schedulePath, { ...breakBody, breaks: breaks.map((day) => ({ ...day, endsAt: day.weekday === 1 ? "14:00" : day.endsAt })) }, activeAdminCookie)).status, 400);
    const breakResponse = await saveSchedule(breakBody);
    assert.equal(breakResponse.status, 200);
    assert.equal((await breakResponse.json()).version, scheduleBaseVersion + 3);
    const nextMonday = new Date(scheduleDate);
    while (nextMonday.getUTCDay() !== 1) nextMonday.setUTCDate(nextMonday.getUTCDate() + 1);
    const nextSunday = new Date(scheduleDate);
    while (nextSunday.getUTCDay() !== 0) nextSunday.setUTCDate(nextSunday.getUTCDate() + 1);
    const nextTuesday = new Date(scheduleDate);
    while (nextTuesday.getUTCDay() !== 2) nextTuesday.setUTCDate(nextTuesday.getUTCDate() + 1);
    assert.equal((await getEffectiveTherapistBreak(prisma, scheduledTherapist.id, nextMonday.toISOString().slice(0, 10)))?.startsAt?.getUTCHours(), 12);
    assert.equal((await getEffectiveTherapistBreak(prisma, scheduledTherapist.id, nextSunday.toISOString().slice(0, 10)))?.startsAt, null);
    assert.equal((await getEffectiveBusinessDay(prisma, nextSunday.toISOString().slice(0, 10)))?.isOpen, false);
    assert.deepEqual((await getAssignableTherapistsForDate(prisma, nextMonday.toISOString().slice(0, 10))).map((person) => person.id), [scheduledTherapist.id]);
    assert.equal((await getEffectiveBusinessDay(prisma, nextTuesday.toISOString().slice(0, 10)))?.isOpen, true);
    assert.deepEqual(await getAssignableTherapistsForDate(prisma, nextTuesday.toISOString().slice(0, 10)), []);
    const overrideDate = new Date(nextMonday);
    const overrideText = overrideDate.toISOString().slice(0, 10);
    const openOverrideDate = new Date(overrideDate.getTime() + 24 * 60 * 60_000);
    const openOverrideText = openOverrideDate.toISOString().slice(0, 10);
    const overrideBody = { kind: "BUSINESS_DATE", effectiveDate: overrideText, expectedVersion: scheduleBaseVersion + 3, reason: "Close one day", isOpen: false, opensAt: null, closesAt: "16:00" };
    const bookedRoom = await prisma.room.create({ data: { name: "Schedule test room" } });
    const bookedStart = new Date(`${overrideText}T01:00:00.000Z`);
    const bookedEnd = new Date(bookedStart.getTime() + 60 * 60_000);
    const booked = await prisma.reservation.create({ data: { memberId: member.id, treatmentId: activeTreatment.id, roomId: bookedRoom.id, therapistId: scheduledTherapist.id, memberLastNameSnapshot: "Test", memberFirstNameSnapshot: "Member", memberEmailSnapshot: member.email, memberPhoneNumberSnapshot: member.phoneNumber, treatmentNameSnapshot: activeTreatment.name, treatmentDurationMinutesSnapshot: 60, treatmentPriceYenSnapshot: 1000, roomNameSnapshot: bookedRoom.name, therapistNameSnapshot: scheduledTherapist.name, businessDate: overrideDate, startsAt: bookedStart, treatmentEndsAt: bookedEnd, occupiesUntil: bookedEnd, totalDurationMinutes: 60, totalPriceYen: 1000, slotCount: 1 } });
    await prisma.reservationSlot.create({ data: { reservationId: booked.id, roomId: bookedRoom.id, therapistId: scheduledTherapist.id, slotStartsAt: bookedStart } });
    const nextStart = new Date(`${openOverrideText}T01:00:00.000Z`);
    const nextEnd = new Date(nextStart.getTime() + 60 * 60_000);
    const nextBooking = await prisma.reservation.create({ data: { memberId: member.id, treatmentId: activeTreatment.id, roomId: bookedRoom.id, therapistId: scheduledTherapist.id, memberLastNameSnapshot: "Test", memberFirstNameSnapshot: "Member", memberEmailSnapshot: member.email, memberPhoneNumberSnapshot: member.phoneNumber, treatmentNameSnapshot: activeTreatment.name, treatmentDurationMinutesSnapshot: 60, treatmentPriceYenSnapshot: 1000, roomNameSnapshot: bookedRoom.name, therapistNameSnapshot: scheduledTherapist.name, businessDate: openOverrideDate, startsAt: nextStart, treatmentEndsAt: nextEnd, occupiesUntil: nextEnd, totalDurationMinutes: 60, totalPriceYen: 1000, slotCount: 1 } });
    const closureReview = await previewSchedule(overrideBody);
    assert.deepEqual(closureReview.impact.map((row) => ({ id: row.reservationId, before: row.before, after: row.after })), [{ id: booked.id, before: null, after: "BUSINESS_CLOSED" }, { id: nextBooking.id, before: "BREAK_UNSET", after: "BREAK_UNSET" }]);
    await prisma.reservation.update({ where: { id: booked.id }, data: { notes: "Changed after preview", version: { increment: 1 } } });
    assert.equal((await (await mutation(schedulePath, { ...overrideBody, reviewToken: closureReview.reviewToken }, activeAdminCookie)).json()).error, "ReviewRequired");
    const renewedClosureReview = await previewSchedule(overrideBody);
    const overrideResponse = await mutation(schedulePath, { ...overrideBody, reviewToken: renewedClosureReview.reviewToken }, activeAdminCookie);
    assert.equal(overrideResponse.status, 200);
    assert.equal((await overrideResponse.json()).version, scheduleBaseVersion + 4);
    assert.equal(await prisma.reservationChangeNotice.count({ where: { reservationId: booked.id, reason: "BUSINESS_CLOSED" } }), 1);
    assert.equal(await prisma.reservationChangeNotice.count({ where: { reservationId: nextBooking.id } }), 0);
    assert.match(JSON.stringify((await prisma.auditLog.findFirstOrThrow({ where: { action: "SCHEDULE_CREATED", targetType: "SchedulePlan", targetId: (await prisma.schedulePlan.findFirstOrThrow({ where: { kind: "BUSINESS_DATE", effectiveDate: overrideDate } })).id } })).changes), new RegExp(nextBooking.id));
    assert.equal(await prisma.reservationSlot.count({ where: { reservationId: booked.id } }), 1);
    assert.equal((await prisma.reservation.findUniqueOrThrow({ where: { id: booked.id } })).status, "CONFIRMED");
    assert.equal((await getEffectiveBusinessDay(prisma, overrideText))?.isOpen, false);
    assert.equal((await getEffectiveBusinessDay(prisma, openOverrideText))?.source, "WEEKLY");
    const openOverrideResponse = await saveSchedule({ kind: "BUSINESS_DATE", effectiveDate: openOverrideText, expectedVersion: scheduleBaseVersion + 4, reason: "Open with shorter hours", isOpen: true, opensAt: "10:00", closesAt: "16:00" });
    assert.equal(openOverrideResponse.status, 200);
    assert.equal((await openOverrideResponse.json()).version, scheduleBaseVersion + 5);
    assert.equal((await getEffectiveBusinessDay(prisma, openOverrideText))?.opensAt?.getUTCHours(), 10);
    assert.equal((await getEffectiveBusinessDay(prisma, openOverrideText))?.closesAt.getUTCHours(), 16);
    const upcoming = await (await protectedGet(schedulePath, activeAdminCookie)).json() as { upcoming: { id: string; revision: number; effectiveDate: string; canceled: boolean }[] };
    assert(upcoming.upcoming.some((plan) => plan.id === weeklySaved.planId && plan.revision === 2 && !plan.canceled));
    const cancelBody = { planId: (await prisma.schedulePlan.findFirstOrThrow({ where: { kind: "BUSINESS_DATE", effectiveDate: overrideDate } })).id, expectedVersion: scheduleBaseVersion + 5, expectedRevision: 1, reason: "Reopen the day" };
    const cancelPreviewResponse = await fetch(`${origin}/api/manage/schedules/cancel`, { method: "PUT", headers: { cookie: activeAdminCookie, origin, "content-type": "application/json" }, body: JSON.stringify(cancelBody) });
    assert.equal(cancelPreviewResponse.status, 200);
    const cancelReview = await cancelPreviewResponse.json() as { reviewToken: string; impact: { reservationId: string; before: string | null; after: string | null }[] };
    assert.deepEqual(cancelReview.impact.map((row) => ({ id: row.reservationId, before: row.before, after: row.after })), [{ id: booked.id, before: "BUSINESS_CLOSED", after: null }, { id: nextBooking.id, before: "BREAK_UNSET", after: "BREAK_UNSET" }]);
    const cancelResponse = await mutation("/api/manage/schedules/cancel", { ...cancelBody, reviewToken: cancelReview.reviewToken }, activeAdminCookie);
    assert.equal(cancelResponse.status, 200);
    assert.equal((await getEffectiveBusinessDay(prisma, overrideText))?.source, "WEEKLY");
    const effectiveView = await (await protectedGet(`${schedulePath}?date=${overrideText}`, activeAdminCookie)).json() as { business: { source: string }; therapists: { id: string; assignable: boolean }[] };
    assert.equal(effectiveView.business.source, "WEEKLY");
    assert.equal(effectiveView.therapists.find((person) => person.id === scheduledTherapist.id)?.assignable, true);
    assert.equal((await prisma.reservationChangeNotice.findFirstOrThrow({ where: { reservationId: booked.id, reason: "BUSINESS_CLOSED" } })).responseStatus, "IMPACT_RESOLVED_PENDING_REVIEW");
    assert.equal(await prisma.reservationSlot.count({ where: { reservationId: booked.id } }), 1);
    assert.match(await (await protectedGet("/manage/adjustments", activeAdminCookie)).text(), /影響解消・店舗確認待ち/);
    assert.equal(await prisma.schedulePlan.count(), 4);
    assert.equal(await prisma.scheduleSettingChange.count(), 6);
    assert.equal(await prisma.auditLog.count({ where: { action: "SCHEDULE_CREATED" } }), 4);
    assert.equal(await prisma.auditLog.count({ where: { action: "SCHEDULE_REVISED" } }), 1);
    assert.equal(await prisma.auditLog.count({ where: { action: "SCHEDULE_CANCELED" } }), 1);
    assert.equal(await prisma.emailDelivery.count({ where: { kind: "RESERVATION_CHANGE" } }), 1);
    const nearBody = { ...weeklyBody, effectiveDate: nearDate, expectedVersion: scheduleBaseVersion + 6, reason: "Near-term exception" };
    const nearReview = await previewSchedule(nearBody);
    assert.equal(nearReview.mode, "NEAR_TERM");
    const nearSave = await mutation(schedulePath, { ...nearBody, reviewToken: nearReview.reviewToken }, activeAdminCookie);
    assert.equal(nearSave.status, 200);
    assert.equal((await nearSave.json()).mode, "NEAR_TERM");
    await prisma.staffAccount.update({ where: { id: staff.id }, data: { authVersion: 2 } });
    assert.equal(await (await call("session")).json(), null);
    assert.equal((await protectedGet("/api/manage/staff")).status, 401);
    await login("staff", "staff@example.test", password);
    await prisma.staffAccount.update({ where: { id: staff.id }, data: { isActive: false } });
    assert.equal(await (await call("session")).json(), null);
    assert.equal((await protectedGet("/api/manage/staff")).status, 401);
    assert.match((await (await login("staff", "staff@example.test", password)).json()).url, /CredentialsSignin/);
    await resetAttempts();
    const attempts = await Promise.allSettled(Array.from({ length: 6 }, () => consumeLoginAttempt("STAFF", "parallel@example.test", new Request(origin))));
    for (const attempt of attempts) if (attempt.status === "rejected" && !(attempt.reason instanceof LoginRateLimited)) console.error("Concurrent attempt failure:", attempt.reason.name, attempt.reason.code);
    assert.equal(attempts.filter(x => x.status === "fulfilled").length, 5);
    assert.equal(attempts.filter(x => x.status === "rejected" && x.reason instanceof LoginRateLimited).length, 1);
    const limited = await login("staff", "parallel@example.test", password);
    assert.equal(limited.status, 429);
    assert.equal(limited.headers.get("retry-after"), "900");
    // Expired events no longer count; success does not clear the counters.
    await prisma.rateLimitEvent.updateMany({ data: { occurredAt: new Date(Date.now() - 16 * 60_000) } });
    assert.equal((await login("staff", "parallel@example.test", password)).status, 200);
    await resetAttempts();
    await prisma.staffAccount.update({ where: { id: staff.id }, data: { isActive: true } });
    await login("staff", "staff@example.test", password);
    const beforeFailureCookie = cookie();
    const logoutCsrf = await (await call("csrf")).json();
    // Missing table simulates a DB read/write failure without interrupting the real DB.
    await pg.query(`ALTER TABLE "${schema}"."AppSession" RENAME TO "UnavailableSession"`);
    try {
      assert.equal((await call("session")).status, 503);
      assert.equal((await protectedGet("/api/manage/staff")).status, 503);
      const failedLogout = await call("signout", { csrfToken: logoutCsrf.csrfToken });
      assert.equal(failedLogout.status, 503);
      assert.equal(failedLogout.headers.getSetCookie().length, 0);
      assert.equal(cookie(), beforeFailureCookie);
    } finally { await pg.query(`ALTER TABLE "${schema}"."UnavailableSession" RENAME TO "AppSession"`); }
    assert.equal((await call("signout", { csrfToken: logoutCsrf.csrfToken })).status, 200);
    console.log("Integration passed: authentication, resources, schedule previews/history/cancellation, reservation impact and effective-day eligibility over HTTP (isolated schema).");
  } finally {
    if (server && server.exitCode === null) { server.kill("SIGTERM"); await once(server, "exit"); }
    await prisma?.$disconnect();
    await pg.query(`DROP SCHEMA IF EXISTS "${schema}" CASCADE`);
    await pg.end();
    rmSync(distDir, { recursive: true, force: true });
  }
}
main().catch((error: unknown) => { if (error instanceof Error) console.error(error.name, error.stack?.split("\n").filter(line => line.trim().startsWith("at ")).join("\n")); console.error("Auth integration failed; inspect test assertions without logging credentials."); process.exitCode = 1; });
