import assert from "node:assert/strict";
import { randomBytes, randomUUID } from "node:crypto";
import { spawn, type ChildProcess } from "node:child_process";
import { createServer } from "node:net";
import { once } from "node:events";
import { mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { Client } from "pg";
import { PrismaPg } from "@prisma/adapter-pg";
import { PrismaClient } from "../src/generated/prisma/client";
import { loadDevelopmentDatabase, runPrisma } from "./lib/development-database";
import { ADMIN_ID } from "../src/lib/auth/policy";

async function main() {
  const connectionString = loadDevelopmentDatabase();
  const schema = `member_verify_${randomUUID().replaceAll("-", "")}`;
  const pg = new Client({ connectionString }); await pg.connect();
  const distDir = `.next-member-test-${schema}`;
  let db: PrismaClient | undefined;
  let server: ChildProcess | undefined;
  try {
    await pg.query(`CREATE SCHEMA "${schema}"`);
    const url = new URL(connectionString); url.searchParams.set("schema", schema);
    runPrisma(["migrate", "deploy"], url.href);
    process.env.DATABASE_URL = url.href;
    db = new PrismaClient({ adapter: new PrismaPg({ connectionString }, { schema }), log: [] });
    (globalThis as unknown as { bookingPrisma: PrismaClient }).bookingPrisma = db;
    const portProbe = createServer(); portProbe.listen(0, "127.0.0.1"); await once(portProbe, "listening");
    const port = (portProbe.address() as {port:number}).port;
    await new Promise<void>((done) => portProbe.close(() => done()));
    const origin = `http://127.0.0.1:${port}`;
    process.env.AUTH_URL = origin;
    process.env.AUTH_SECRET = randomBytes(32).toString("hex");
    process.env.AUTH_RATE_LIMIT_SECRET = randomBytes(32).toString("hex");
    process.env.MAIL_PAYLOAD_KEY = randomBytes(32).toString("base64");
    process.env.RESEND_FROM = "mail@example.test";
    process.env.RESEND_API_KEY = "re_test_local_only";
    process.env.MAIL_TEST_DISABLE_IMMEDIATE = "1";
    process.env.CRON_SECRET = randomBytes(24).toString("base64url");
    process.env.ADMIN_EMAIL = "admin@example.test";
    process.env.ADMIN_PASSWORD = randomBytes(24).toString("base64url");
    process.env.ADMIN_AUTH_VERSION = "1";
    await db.adminAccount.create({ data: { id: ADMIN_ID, displayName: "Test administrator" } });
    mkdirSync(distDir);
    const tsconfig = JSON.parse(readFileSync("tsconfig.json", "utf8"));
    tsconfig.include = [resolve("src/**/*.ts"), resolve("src/**/*.tsx"), resolve("next-env.d.ts")];
    tsconfig.compilerOptions.baseUrl = process.cwd();
    tsconfig.compilerOptions.paths = { "@/*": ["./src/*"] };
    writeFileSync(`${distDir}/tsconfig.json`, JSON.stringify(tsconfig));
    server = spawn(process.execPath, ["node_modules/next/dist/bin/next", "dev", "--webpack", "-p", String(port), "-H", "127.0.0.1"], { env: { ...process.env, NODE_OPTIONS: "", NEXT_DIST_DIR: distDir, AUTH_TEST_TSCONFIG: `${distDir}/tsconfig.json` }, stdio: ["ignore", "pipe", "pipe"] });
    let output = ""; server.stdout?.on("data", (part) => { output = (output + String(part)).slice(-8000); }); server.stderr?.on("data", (part) => { output = (output + String(part)).slice(-8000); });
    let ready = false;
    for (let i=0;i<90;i++) { try { if ((await fetch(`${origin}/api/auth/csrf`)).ok) { ready=true; break; } } catch {} if (server.exitCode !== null) break; await new Promise((done) => setTimeout(done,500)); }
    if (!ready) process.stderr.write(output.replaceAll(process.env.ADMIN_PASSWORD, "[redacted]"));
    assert(ready, "Test server did not become ready");
    const { decryptMailPayload } = await import("../src/lib/member/mail");
    const { runMailBatch } = await import("../src/lib/mail/worker");
    const { resolveSession } = await import("../src/lib/auth/session");
    const { getToken, encode } = await import("next-auth/jwt");
    const jar = new Map<string,string>();
    const cookie = () => [...jar].map(([k,v])=>`${k}=${v}`).join("; ");
    async function auth(path: string, body?: Record<string,string>, customCookie = cookie()) {
      const response = await fetch(`${origin}/api/auth/${path}`, { method: body ? "POST" : "GET", headers: { cookie: customCookie, origin, ...(body ? { "content-type": "application/x-www-form-urlencoded", "x-auth-return-redirect": "1" } : {}) }, ...(body ? { body: new URLSearchParams(body) } : {}) });
      for (const raw of response.headers.getSetCookie()) { const [key, ...rest] = raw.split(";")[0].split("="); const value = rest.join("="); if (value) jar.set(key,value); else jar.delete(key); }
      return response;
    }
    async function login(email: string, password: string) { const csrf = await (await auth("csrf")).json(); return auth("callback/member", { email, password, csrfToken: csrf.csrfToken, callbackUrl: "/account" }); }
    async function post(path: string, body: object) { return fetch(`${origin}/api/member/${path}`, { method: "POST", headers: { origin, "content-type": "application/json" }, body: JSON.stringify(body) }); }
    async function tokenFor(emailKey: string) { const delivery = await db!.emailDelivery.findFirstOrThrow({ where: { recipient: emailKey, encryptedPayload: { not: null } }, orderBy: { createdAt: "desc" } }); const text = decryptMailPayload(delivery.encryptedPayload!).text; return text.match(/#token=([A-Za-z0-9_-]{43})/)?.[1] ?? ""; }
    const password = "temporary-password-123456";
    const freshPassword = "confirmed-password-123456";
    const details = { email: "first@example.test", lastName: "山田", firstName: "花子", phoneNumber: "09012345678", postalCode: "123-4567", ageBand: 30, password };
    const firstRegistration = await post("register", details);
    assert.equal(firstRegistration.status, 200, `${await firstRegistration.text()}\n${output}`);
    const duplicateRegistration = await post("register", { ...details, lastName: "別人" });
    assert.equal(duplicateRegistration.status, 409);
    assert.equal((await duplicateRegistration.json()).error, "EmailAlreadyRegistered");
    assert.equal(await db.member.count({ where: { emailKey: details.email } }), 1);
    assert.equal(await db.emailDelivery.count({ where: { recipient: details.email } }), 1);
    let member = await db.member.findUniqueOrThrow({ where: { emailKey: details.email } });
    assert.equal(member.status, "PENDING_EMAIL");
    assert.equal(member.lastName, "山田");
    assert.match((await (await login(details.email,password)).json()).url, /CredentialsSignin/);
    const firstToken = await tokenFor(details.email);
    assert(firstToken);
    const firstDelivery = await db.emailDelivery.findFirstOrThrow({ where: { recipient: details.email }, select: { id: true } });
    const sentKeys: string[] = [];
    await Promise.all([runMailBatch(async (payload, key) => { assert.equal(payload.to, details.email); sentKeys.push(key); return { kind: "ACCEPTED" }; }, 1, db, firstDelivery.id), runMailBatch(async (_payload, key) => { sentKeys.push(key); return { kind: "ACCEPTED" }; }, 1, db, firstDelivery.id)]);
    assert.equal(sentKeys.length, 1);
    assert.equal((await db.emailDelivery.findFirstOrThrow({ where: { recipient: details.email } })).status, "ACCEPTED");
    await db.rateLimitBucket.updateMany({ where: { scope: "MAIL_ADDRESS" }, data: { lastAttemptAt: new Date(0) } });
    assert.equal((await post("resend", { email: details.email })).status, 200);
    const confirmation = await tokenFor(details.email);
    assert.notEqual(confirmation, firstToken);
    assert.equal((await post("confirm", { token: firstToken, password: freshPassword })).status, 409);
    assert.equal((await post("confirm", { token: confirmation, password: freshPassword })).status, 200);
    assert.equal((await post("confirm", { token: confirmation, password: freshPassword })).status, 409);
    member = await db.member.findUniqueOrThrow({ where: { emailKey: details.email } });
    assert.equal(member.status, "ACTIVE");
    assert(member.emailVerifiedAt);
    assert.match((await (await login(details.email,password)).json()).url, /CredentialsSignin/);
    assert.equal((await login(details.email,freshPassword)).status, 200);
    const memberCookie = cookie();
    const session = await (await auth("session")).json();
    assert.equal(session.user.role, "MEMBER");
    assert.equal(session.user.id, member.id);
    assert.equal((await fetch(`${origin}/api/manage/staff`, { headers: { cookie: memberCookie } })).status, 403);
    assert.equal((await fetch(`${origin}/api/manage/staff/${member.id}/permissions`, { method: "POST", headers: { cookie: memberCookie, origin, "content-type": "application/json" }, body: JSON.stringify({ permission: "ROOM_CREATE", enabled: true }) })).status, 403);
    assert.match(await (await fetch(`${origin}/account`, { headers: { cookie: memberCookie } })).text(), /マイページ/);
    assert.equal((await fetch(`${origin}/manage`, { headers: { cookie: memberCookie }, redirect: "manual" })).status, 200);
    assert.match(await (await fetch(`${origin}/manage`, { headers: { cookie: memberCookie } })).text(), /権限がありません/);
    const jwt = await getToken({ req: new Request(origin, { headers: { cookie: memberCookie } }), secret: process.env.AUTH_SECRET, secureCookie: false });
    assert(jwt);
    assert.equal(await resolveSession(jwt, new Date(Number(jwt.absoluteExpiry))), null);
    const expiredJwt = await encode({ token: { ...jwt, absoluteExpiry: Date.now()-1000 }, secret: process.env.AUTH_SECRET, salt: "authjs.session-token", maxAge: 7*24*60*60 });
    assert.equal(await (await auth("session", undefined, `authjs.session-token=${expiredJwt}`)).json(), null);
    await db.rateLimitBucket.updateMany({ where: { scope: "MAIL_ADDRESS" }, data: { lastAttemptAt: new Date(0) } });
    assert.equal((await post("reset-request", { email: details.email })).status, 200);
    assert.equal((await post("reset-request", { email: "unknown@example.test" })).status, 200);
    const reset = await tokenFor(details.email);
    assert.equal((await runMailBatch(async (payload) => { assert.equal(payload.to, details.email); assert.match(payload.text, /パスワード再設定/); return { kind: "ACCEPTED" }; }, 1, db)).attempted, 1);
    await db.authToken.update({ where: { digest: (await import("../src/lib/member/mail")).tokenDigest(reset) }, data: { createdAt: new Date(Date.now()-30*60_000), expiresAt: new Date(Date.now()-1000) } });
    assert.equal((await post("reset", { token: reset, password: "reset-password-123456" })).status, 409);
    const expired = await db.authToken.findUniqueOrThrow({ where: { digest: (await import("../src/lib/member/mail")).tokenDigest(reset) } });
    assert.equal(expired.usedAt, null);
    // Use a distinct address to avoid the 60-second shared email throttle.
    const second = { ...details, email: "second@example.test", firstName: "太郎" };
    assert.equal((await post("register", second)).status, 200);
    const secondToken = await tokenFor(second.email);
    assert.equal((await post("confirm", { token: secondToken, password: freshPassword })).status, 200);
    await db.member.update({ where: { emailKey: second.email }, data: { status: "WITHDRAWN", isDeleted: true } });
    const review = { ...details, email: "review@example.test", firstName: "太郎" };
    assert.equal((await post("register", review)).status, 200);
    assert.equal((await post("confirm", { token: await tokenFor(review.email), password: freshPassword })).status, 200);
    assert.equal((await db.member.findUniqueOrThrow({ where: { emailKey: review.email } })).status, "PENDING_REVIEW");
    assert.equal(await db.memberReview.count({ where: { member: { emailKey: review.email } } }), 1);
    assert.match((await (await login(review.email, freshPassword)).json()).url, /CredentialsSignin/);
    await db.member.update({ where: { id: member.id }, data: { status: "WITHDRAWN", isDeleted: true } });
    assert.equal(await (await auth("session", undefined, memberCookie)).json(), null);
    assert.doesNotMatch(await (await fetch(`${origin}/account`, { headers: { cookie: memberCookie } })).text(), /ログイン中です/);
    const withdrawnRegistration = await post("register", details);
    assert.equal(withdrawnRegistration.status, 409);
    assert.equal((await withdrawnRegistration.json()).error, "EmailAlreadyRegistered");
    assert.equal(await db.member.count({ where: { emailKey: details.email } }), 1);
    // Fresh active account: successful reset invalidates its live session.
    await db.member.update({ where: { id: member.id }, data: { status: "ACTIVE", isDeleted: false } });
    await db.rateLimitBucket.deleteMany();
    assert.equal((await post("reset-request", { email: details.email })).status, 200);
    const reset2 = await tokenFor(details.email);
    assert.equal((await post("reset", { token: reset2, password: "reset-password-123456" })).status, 200);
    assert.equal(await (await auth("session", undefined, memberCookie)).json(), null);
    assert.equal((await post("reset", { token: reset2, password: "reset-password-123456" })).status, 409);
    assert.equal((await login(details.email, "reset-password-123456")).status, 200);
    const csrf = await (await auth("csrf")).json();
    assert.equal((await auth("signout", { csrfToken: csrf.csrfToken, callbackUrl: "/login" })).status, 200);
    assert.equal(await (await auth("session")).json(), null);
    assert.equal((await post("register", { ...details, ageBand: 10 })).status, 400);
    await db.emailDelivery.updateMany({ where: { status: { in: ["PENDING", "RETRY_WAIT"] } }, data: { status: "CANCELLED", encryptedPayload: null, payloadKeyId: null, payloadExpiresAt: null, nextAttemptAt: null, closedAt: new Date() } });
    await db.member.update({ where: { id: member.id }, data: { status: "WITHDRAWN", isDeleted: true, version: { increment: 1 } } });
    await db.rateLimitBucket.updateMany({ where: { scope: "MAIL_ADDRESS" }, data: { lastAttemptAt: new Date(0) } });
    const adminCsrf = await (await auth("csrf")).json();
    assert.equal((await auth("callback/admin", { email: process.env.ADMIN_EMAIL!, password: process.env.ADMIN_PASSWORD!, csrfToken: adminCsrf.csrfToken, callbackUrl: "/manage" })).status, 200);
    const withdrawn = await db.member.findUniqueOrThrow({ where: { id: member.id } });
    const restoreResponse = await fetch(`${origin}/api/manage/members/${member.id}/restore`, { method: "POST", headers: { cookie: cookie(), origin, "content-type": "application/json" }, body: JSON.stringify({ expectedVersion: withdrawn.version, reason: "本人からの復旧依頼" }) });
    assert.equal(restoreResponse.status, 200, await restoreResponse.text());
    const restore1 = await tokenFor(details.email);
    assert.equal((await db.member.findUniqueOrThrow({ where: { id: member.id } })).status, "RESTORE_PENDING");
    assert.equal((await runMailBatch(async (payload) => { assert.equal(payload.to, details.email); assert.match(payload.text, /復旧確認/); return { kind: "ACCEPTED" }; }, 1, db)).attempted, 1);
    await db.rateLimitBucket.updateMany({ where: { scope: "MAIL_ADDRESS" }, data: { lastAttemptAt: new Date(0) } });
    assert.equal((await post("restore-resend", { email: details.email })).status, 200);
    const restore2 = await tokenFor(details.email);
    assert.notEqual(restore1, restore2);
    assert.equal((await post("restore", { token: restore1, password: "restored-password-123456" })).status, 409);
    assert.equal((await post("restore", { token: restore2, password: "restored-password-123456" })).status, 200);
    assert.equal((await post("restore", { token: restore2, password: "restored-password-123456" })).status, 409);
    assert.equal((await db.member.findUniqueOrThrow({ where: { id: member.id } })).status, "ACTIVE");
    assert.equal(await db.memberLifecycleEvent.count({ where: { memberId: member.id, kind: { in: ["RESTORE_REQUESTED", "RESTORE_COMPLETED"] } } }), 2);
    await db.emailDelivery.updateMany({ where: { status: { in: ["PENDING", "RETRY_WAIT"] } }, data: { status: "CANCELLED", encryptedPayload: null, payloadKeyId: null, payloadExpiresAt: null, nextAttemptAt: null, closedAt: new Date() } });
    const mailCase = { ...details, email: "mail-case@example.test" };
    assert.equal((await post("register", mailCase)).status, 200);
    const queued = await db.emailDelivery.findFirstOrThrow({ where: { recipient: mailCase.email } });
    for (let i = 1; i <= 4; i++) {
      const result = await runMailBatch(async (_payload, key) => { assert.equal(key, queued.requestKey); return { kind: "TRANSIENT", code: "RATE_LIMITED" }; }, 1, db);
      assert.equal(result.attempted, 1);
      const delivery: { status: string } = await db.emailDelivery.findUniqueOrThrow({ where: { id: queued.id }, select: { status: true } });
      assert.equal(delivery.status, i < 4 ? "RETRY_WAIT" : "FAILED");
      if (i < 4) {
        const timing = await db.emailDelivery.findUniqueOrThrow({ where: { id: queued.id }, select: { nextAttemptAt: true, updatedAt: true } });
        assert(Math.abs(timing.nextAttemptAt!.getTime() - timing.updatedAt.getTime() - [60_000, 5 * 60_000, 30 * 60_000][i-1]) < 2000);
      }
      if (i < 4) await db.emailDelivery.update({ where: { id: queued.id }, data: { nextAttemptAt: new Date() } });
    }
    assert.equal(await db.emailDeliveryAttempt.count({ where: { deliveryId: queued.id } }), 4);
    assert.equal((await db.emailDelivery.findUniqueOrThrow({ where: { id: queued.id } })).encryptedPayload, null);
    assert.equal((await post("register", { ...details, email: "unknown-result@example.test" })).status, 200);
    const unknownCase = await db.emailDelivery.findFirstOrThrow({ where: { recipient: "unknown-result@example.test" } });
    assert.equal((await runMailBatch(async () => ({ kind: "UNKNOWN", code: "NETWORK_UNCERTAIN" }), 1, db)).attempted, 1);
    assert.equal((await db.emailDelivery.findUniqueOrThrow({ where: { id: unknownCase.id } })).status, "UNKNOWN");
    assert.equal((await runMailBatch(async () => { throw new Error("Must not retry unknown"); }, 1, db)).attempted, 0);
    assert.equal((await post("register", { ...details, email: "expired-mail@example.test" })).status, 200);
    const expiredMail = await db.emailDelivery.findFirstOrThrow({ where: { recipient: "expired-mail@example.test" }, include: { token: true } });
    await db.authToken.update({ where: { id: expiredMail.tokenId! }, data: { createdAt: new Date(Date.now() - 23 * 60 * 60_000), expiresAt: new Date(Date.now() - 1000) } });
    assert.equal((await runMailBatch(async () => { throw new Error("Expired token must not send"); }, 1, db)).attempted, 0);
    assert.equal((await db.emailDelivery.findUniqueOrThrow({ where: { id: expiredMail.id } })).status, "EXPIRED");
    assert.equal((await post("register", { ...details, email: "stale-lease@example.test" })).status, 200);
    const staleMail = await db.emailDelivery.findFirstOrThrow({ where: { recipient: "stale-lease@example.test" } });
    const leaseId = randomUUID();
    await db.emailDelivery.update({ where: { id: staleMail.id }, data: { createdAt: new Date(Date.now() - 2 * 60_000), status: "SENDING", attemptCount: 1, nextAttemptAt: null, leaseId, leaseExpiresAt: new Date(Date.now() - 1000) } });
    await db.emailDeliveryAttempt.create({ data: { deliveryId: staleMail.id, attemptNumber: 1, leaseId, startedAt: new Date(Date.now() - 90_000) } });
    const staleRun = await runMailBatch(async () => { throw new Error("Uncertain prior send must not retry"); }, 1, db);
    assert.equal(staleRun.stale, 1);
    assert.equal(staleRun.attempted, 0);
    assert.equal((await db.emailDelivery.findUniqueOrThrow({ where: { id: staleMail.id } })).status, "UNKNOWN");
    assert.equal((await fetch(`${origin}/api/cron/mail`)).status, 401);
    assert.equal((await fetch(`${origin}/api/cron/mail`, { headers: { authorization: `Bearer ${process.env.CRON_SECRET}` } })).status, 200);
    process.stdout.write("Member registration, review, auth boundaries, expiry, reset and logout passed.\n");
  } finally {
    if (server) { server.kill("SIGTERM"); await once(server,"exit").catch(()=>{}); }
    await db?.$disconnect();
    if (distDir) rmSync(distDir, { recursive:true, force:true });
    await pg.query(`DROP SCHEMA IF EXISTS "${schema}" CASCADE`);
    await pg.end();
  }
}
main().catch((error: unknown) => {
  // Assertion messages can contain response bodies, tokens and member snapshots.
  if (error instanceof Error) process.stderr.write(`${error.name}\n${error.stack?.split("\n").filter(line => line.trim().startsWith("at ")).join("\n") ?? ""}\n`);
  process.stderr.write("Integration failed; inspect assertions locally without logging response bodies.\n");
  process.exitCode = 1;
});
