import assert from "node:assert/strict";
import { randomBytes, randomUUID } from "node:crypto";
import { spawn, type ChildProcess } from "node:child_process";
import { createServer } from "node:net";
import { once } from "node:events";
import { mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { Client } from "pg";
import { PrismaPg } from "@prisma/adapter-pg";
import { PrismaClient } from "../src/generated/prisma/client";
import { loadDevelopmentDatabase, runPrisma } from "./lib/development-database";
import { seedDevelopment, seedIds } from "../prisma/seed-data";
import { tokyoBusinessDate, parseBusinessDate } from "../src/lib/schedules/calendar";
import { tokyoInstant } from "../src/lib/booking/availability-core";
import { ADMIN_ID } from "../src/lib/auth/policy";
import { encode } from "next-auth/jwt";

function dayAfter(days: number) {
  const date = new Date(parseBusinessDate(tokyoBusinessDate(new Date())).getTime() + days * 86_400_000);
  while (date.getUTCDay() === 0) date.setUTCDate(date.getUTCDate() + 1);
  return date.toISOString().slice(0, 10);
}
const iso = (date: string, hour: number) => new Date(tokyoInstant(date, hour)).toISOString();

async function main() {
  const connectionString = loadDevelopmentDatabase();
  const schema = `booking_verify_${randomUUID().replaceAll("-", "")}`;
  const pg = new Client({ connectionString });
  await pg.connect();
  const distDir = `.next-booking-test-${schema}`;
  let db: PrismaClient | undefined;
  let server: ChildProcess | undefined;
  try {
    await pg.query(`CREATE SCHEMA "${schema}"`);
    const url = new URL(connectionString); url.searchParams.set("schema", schema);
    runPrisma(["migrate", "deploy"], url.href);
    process.env.DATABASE_URL = url.href;
    db = new PrismaClient({ adapter: new PrismaPg({ connectionString }, { schema }), log: [] });
    await seedDevelopment(db);
    await db.room.update({ where: { id: seedIds.rooms[1] }, data: { isActive: false } });
    await db.therapist.update({ where: { id: seedIds.therapists[1] }, data: { isActive: false } });
    const member = await db.member.create({ data: { email: "booking@example.test", emailKey: "booking@example.test", lastName: "予約", firstName: "花子", lastNameKey: "予約", firstNameKey: "花子", phoneNumber: "09012345678", postalCode: "0010000", ageBand: 30, passwordHash: "test-only-not-a-login-hash", status: "ACTIVE", emailVerifiedAt: new Date(), firstActivatedAt: new Date() } });
    const other = await db.member.create({ data: { email: "other@example.test", emailKey: "other@example.test", lastName: "別", firstName: "会員", lastNameKey: "別", firstNameKey: "会員", phoneNumber: "09011112222", postalCode: "0010000", ageBand: 30, passwordHash: "test-only-not-a-login-hash", status: "ACTIVE", emailVerifiedAt: new Date(), firstActivatedAt: new Date() } });
    const staff = await db.staffAccount.create({ data: { email: "booking-staff@example.test", emailKey: "booking-staff@example.test", displayName: "予約担当", passwordHash: "test-only-not-a-login-hash" } });
    const portProbe = createServer(); portProbe.listen(0, "127.0.0.1"); await once(portProbe, "listening");
    const port = (portProbe.address() as { port: number }).port;
    await new Promise<void>(done => portProbe.close(() => done()));
    const origin = `http://127.0.0.1:${port}`;
    process.env.AUTH_URL = origin;
    process.env.AUTH_SECRET = randomBytes(32).toString("hex");
    process.env.AUTH_RATE_LIMIT_SECRET = randomBytes(32).toString("hex");
    process.env.MAIL_PAYLOAD_KEY = randomBytes(32).toString("base64");
    process.env.RESEND_FROM = "mail@example.test";
    process.env.MAIL_TEST_DISABLE_IMMEDIATE = "1";
    process.env.ADMIN_EMAIL = "admin@example.test";
    process.env.ADMIN_PASSWORD = randomBytes(24).toString("base64url");
    process.env.ADMIN_AUTH_VERSION = "1";
    mkdirSync(distDir);
    const tsconfig = JSON.parse(readFileSync("tsconfig.json", "utf8"));
    tsconfig.include = [resolve("src/**/*.ts"), resolve("src/**/*.tsx"), resolve("next-env.d.ts")];
    tsconfig.compilerOptions.baseUrl = process.cwd();
    tsconfig.compilerOptions.paths = { "@/*": ["./src/*"] };
    writeFileSync(`${distDir}/tsconfig.json`, JSON.stringify(tsconfig));
    server = spawn(process.execPath, ["node_modules/next/dist/bin/next", "dev", "--webpack", "-p", String(port), "-H", "127.0.0.1"], { env: { ...process.env, NODE_OPTIONS: "", NEXT_DIST_DIR: distDir, AUTH_TEST_TSCONFIG: `${distDir}/tsconfig.json` }, stdio: ["ignore", "pipe", "pipe"] });
    let output = ""; server.stdout?.on("data", part => { output = (output + String(part)).slice(-8000); }); server.stderr?.on("data", part => { output = (output + String(part)).slice(-8000); });
    let ready = false;
    for (let i = 0; i < 90; i++) { try { if ((await fetch(`${origin}/api/auth/csrf`)).ok) { ready = true; break; } } catch {} if (server.exitCode !== null) break; await new Promise(done => setTimeout(done, 500)); }
    if (!ready) process.stderr.write(output.replaceAll(process.env.ADMIN_PASSWORD!, "[redacted]"));
    assert(ready, "Test server did not become ready.");
    async function cookie(role: "MEMBER" | "STAFF" | "ADMIN", principalId: string) {
      const expiresAt = new Date(Date.now() + 60 * 60_000);
      const session = await db!.appSession.create({ data: { principalType: role, ...(role === "MEMBER" ? { memberId: principalId } : role === "STAFF" ? { staffId: principalId } : { adminId: principalId }), authVersion: 1, expiresAt } });
      const token = await encode({ token: { sid: session.id, principalId, role, authVersion: 1, absoluteExpiry: expiresAt.getTime() }, secret: process.env.AUTH_SECRET!, salt: "authjs.session-token", maxAge: 3600 });
      return `authjs.session-token=${token}`;
    }
    const memberCookie = await cookie("MEMBER", member.id);
    const otherCookie = await cookie("MEMBER", other.id);
    const adminCookie = await cookie("ADMIN", ADMIN_ID);
    const staffCookie = await cookie("STAFF", staff.id);
    async function send(method: string, path: string, body: object, session = memberCookie) {
      const response = await fetch(`${origin}${path}`, { method, headers: { origin, cookie: session, "content-type": "application/json" }, body: JSON.stringify(body) });
      const result = await response.json() as Record<string, unknown>;
      return { status: response.status, result };
    }
    const date = dayAfter(7);
    const create = (hour: number, optionIds: string[] = []) => ({ requestKey: randomUUID(), date, startsAt: iso(date, hour), treatmentId: seedIds.treatments[0], optionIds, quote: { totalDurationMinutes: optionIds.length ? 70 : 60, totalPriceYen: optionIds.length ? 7000 : 6000 } });
    const availability = await fetch(`${origin}/api/availability?date=${date}&treatmentId=${seedIds.treatments[0]}`);
    assert.equal(availability.status, 200);
    assert((await availability.json() as { times: { startsAt: string }[] }).times.some(time => time.startsAt === iso(date, 9)));
    const calendarResponse = await fetch(`${origin}/api/availability/calendar?treatmentId=${seedIds.treatments[0]}`);
    assert.equal(calendarResponse.status, 200);
    assert.equal(calendarResponse.headers.get("cache-control"), "no-store");
    const bookingCalendar = await calendarResponse.json() as { today: string; endDate: string; days: { date: string; availableCount: number; outsideWindow: boolean }[] };
    assert.equal(bookingCalendar.today, tokyoBusinessDate(new Date()));
    assert.equal(bookingCalendar.days.length, 30);
    assert(bookingCalendar.days.every(day => day.date > bookingCalendar.today && day.date <= bookingCalendar.endDate));
    assert(bookingCalendar.days.find(day => day.date === date)!.availableCount > 0);
    const closedDay = bookingCalendar.days.find(day => parseBusinessDate(day.date).getUTCDay() === 0)!;
    assert.equal(closedDay.availableCount, 0);
    assert.equal((await fetch(`${origin}/api/availability/calendar?treatmentId=invalid`)).status, 400);
    assert.equal((await fetch(`${origin}/api/availability/calendar?treatmentId=${seedIds.treatments[0]}&date=${date}`)).status, 400);
    const withOption = await fetch(`${origin}/api/availability/calendar?treatmentId=${seedIds.treatments[0]}&optionId=${seedIds.options[0]}`);
    assert.equal(withOption.status, 200);
    const optionCalendar = await withOption.json() as typeof bookingCalendar;
    const optionDaily = await fetch(`${origin}/api/availability?date=${date}&treatmentId=${seedIds.treatments[0]}&optionId=${seedIds.options[0]}`).then(response => response.json()) as { times: unknown[] };
    assert.equal(optionCalendar.days.find(day => day.date === date)!.availableCount, optionDaily.times.length);
    // Fill every available time on a separate test day through the real booking API.
    const fullDate = dayAfter(20);
    const fullDay = await fetch(`${origin}/api/availability?date=${fullDate}&treatmentId=${seedIds.treatments[0]}`).then(response => response.json()) as { times: { startsAt: string }[] };
    assert(fullDay.times.length > 0);
    const fullIds: string[] = [];
    for (const slot of fullDay.times) {
      const booked = await send("POST", "/api/reservations", { ...create(9), date: fullDate, startsAt: slot.startsAt });
      assert.equal(booked.status, 201);
      fullIds.push(booked.result.reservationId as string);
    }
    const fullCalendar = await fetch(`${origin}/api/availability/calendar?treatmentId=${seedIds.treatments[0]}`).then(response => response.json()) as typeof bookingCalendar;
    assert.equal(fullCalendar.days.find(day => day.date === fullDate)!.availableCount, 0);
    for (const id of fullIds) assert.equal((await send("DELETE", `/api/reservations/${id}`, { requestKey: randomUUID(), expectedVersion: 1 })).status, 200);
    const reopenedCalendar = await fetch(`${origin}/api/availability/calendar?treatmentId=${seedIds.treatments[0]}`).then(response => response.json()) as typeof bookingCalendar;
    assert.equal(reopenedCalendar.days.find(day => day.date === fullDate)!.availableCount, fullDay.times.length);
    const unauthenticated = await send("POST", "/api/reservations", create(9), "");
    assert.equal(unauthenticated.status, 401, JSON.stringify({ result: unauthenticated.result, input: create(9) }));
    assert.equal((await send("POST", "/api/reservations", { ...create(9), memberId: other.id })).status, 400);
    assert.equal((await send("POST", "/api/reservations", { ...create(11), memberId: member.id }, staffCookie)).status, 403);
    assert.equal((await fetch(`${origin}/api/manage/members?query=booking`, { headers: { cookie: staffCookie } })).status, 403);
    await db.staffPermission.create({ data: { staffId: staff.id, permission: "RESERVATION_CREATE", grantedByAdminId: ADMIN_ID } });
    assert.equal((await send("POST", "/api/reservations", { ...create(11), memberId: member.id }, staffCookie)).status, 201);
    assert.equal((await send("POST", "/api/reservations", { ...create(9), quote: { totalDurationMinutes: 60, totalPriceYen: 1 } })).status, 409);
    const firstBody = create(9);
    const first = await send("POST", "/api/reservations", firstBody);
    assert.equal(first.status, 201, JSON.stringify(first.result));
    const firstId = first.result.reservationId as string;
    const { runMailBatch } = await import("../src/lib/mail/worker");
    const { decryptMailPayload } = await import("../src/lib/member/mail");
    const confirmations = await db.emailDelivery.findMany({ where: { reservationId: firstId }, orderBy: { kind: "asc" } });
    assert.equal(confirmations.length, 2);
    const memberMail = confirmations.find(row => row.kind === "RESERVATION_CONFIRMED_MEMBER")!;
    const adminMail = confirmations.find(row => row.kind === "RESERVATION_CONFIRMED_ADMIN")!;
    const memberPayload = decryptMailPayload(memberMail.encryptedPayload!);
    const adminPayload = decryptMailPayload(adminMail.encryptedPayload!);
    assert.equal(memberPayload.to, member.email);
    assert.equal(adminPayload.to, process.env.ADMIN_EMAIL);
    assert.match(memberPayload.subject, /予約が確定/);
    assert.match(memberPayload.text, /予約 花子 様/);
    assert(memberPayload.text.includes(`${date.replaceAll("-", "/")} 09:00`));
    assert(memberPayload.text.includes(`/account/reservations/${firstId}`));
    assert(adminPayload.text.includes(`/manage/reservations/${firstId}`));
    const confirmationKeys: string[] = [];
    await runMailBatch(async (_payload, key) => { confirmationKeys.push(key); return { kind: "TRANSIENT", code: "RATE_LIMITED" }; }, 1, db, memberMail.id);
    assert.equal((await db.emailDelivery.findUniqueOrThrow({ where: { id: memberMail.id } })).status, "RETRY_WAIT");
    await runMailBatch(async payload => { assert.equal(payload.to, process.env.ADMIN_EMAIL); return { kind: "ACCEPTED" }; }, 1, db, adminMail.id);
    await db.emailDelivery.update({ where: { id: memberMail.id }, data: { nextAttemptAt: new Date() } });
    await runMailBatch(async (_payload, key) => { confirmationKeys.push(key); return { kind: "ACCEPTED" }; }, 1, db, memberMail.id);
    assert.deepEqual(confirmationKeys, [memberMail.requestKey, memberMail.requestKey]);
    assert.equal((await runMailBatch(async () => { assert.fail("Accepted mail must not send again"); }, 1, db, memberMail.id)).attempted, 0);
    assert.equal(await db.emailDelivery.count({ where: { reservationId: firstId, status: "ACCEPTED", encryptedPayload: null } }), 2);
    assert.equal(await db.reservationSlot.count({ where: { reservationId: firstId } }), 1);
    const firstAssignment = await db.reservation.findUniqueOrThrow({ where: { id: firstId } });
    async function storePage(path: string, session: string) {
      const response = await fetch(`${origin}${path}`, { headers: { cookie: session }, redirect: "manual" });
      return { status: response.status, html: await response.text(), location: response.headers.get("location") };
    }
    const storePath = `/manage/reservations?date=${date}`;
    const storeList = await storePage(storePath, staffCookie);
    assert.equal(storeList.status, 200);
    assert(storeList.html.includes(firstId));
    assert(storeList.html.includes("予約一覧・カレンダー"));
    const filtered = await storePage(`${storePath}&roomId=${firstAssignment.roomId}&therapistId=${firstAssignment.therapistId}&status=CONFIRMED`, adminCookie);
    assert.equal(filtered.status, 200);
    assert(filtered.html.includes(firstId));
    const otherDate = new Date(parseBusinessDate(date).getTime() + 86_400_000).toISOString().slice(0, 10);
    assert(!(await storePage(`/manage/reservations?date=${otherDate}`, staffCookie)).html.includes(firstId));
    assert(!(await storePage(`${storePath}&status=COMPLETED`, staffCookie)).html.includes(firstId));
    const noMatch = await storePage(`${storePath}&roomId=${seedIds.rooms[1]}`, staffCookie);
    assert.equal(noMatch.status, 200);
    assert(!noMatch.html.includes(firstId));
    const calendar = await storePage(`${storePath}&view=calendar`, staffCookie);
    assert.equal(calendar.status, 200);
    assert(calendar.html.includes("占有時間"));
    assert(calendar.html.includes(firstId));
    const storeDetail = await storePage(`/manage/reservations/${firstId}`, staffCookie);
    assert.equal(storeDetail.status, 200);
    assert(storeDetail.html.includes("booking@example.test"));
    assert(storeDetail.html.includes("6,000円"));
    const memberStorePage = await storePage(`/manage/reservations/${firstId}`, memberCookie);
    assert(!memberStorePage.html.includes("booking@example.test"));
    const anonymousStorePage = await storePage(`/manage/reservations/${firstId}`, "");
    assert([302, 303, 307, 308].includes(anonymousStorePage.status));
    assert.equal(new URL(anonymousStorePage.location!, origin).pathname, "/staff/login");
    const invalidStoreDetail = await storePage(`/manage/reservations/${randomUUID()}`, staffCookie);
    assert.equal(invalidStoreDetail.status, 404);
    async function read(path: string, session = memberCookie) {
      const response = await fetch(`${origin}${path}`, { headers: { cookie: session }, redirect: "manual" });
      return { status: response.status, result: await response.json() as Record<string, unknown> };
    }
    assert.equal((await read("/api/reservations", "")).status, 401);
    assert.equal((await read(`/api/reservations/${firstId}`, "")).status, 401);
    assert.equal((await read("/api/reservations?memberId=" + member.id)).status, 400);
    const ownList = await read("/api/reservations");
    assert.equal(ownList.status, 200);
    assert((ownList.result.reservations as { id: string }[]).some(row => row.id === firstId));
    assert(!(await read("/api/reservations", otherCookie).then(row => row.result.reservations as { id: string }[])).some(row => row.id === firstId));
    assert.equal((await read(`/api/reservations/${firstId}`, otherCookie)).status, 404);
    assert.equal((await read(`/api/reservations/${randomUUID()}`)).status, 404);
    const ownDetail = await read(`/api/reservations/${firstId}`);
    assert.equal(ownDetail.status, 200);
    assert.equal((ownDetail.result.reservation as { canCancel: boolean }).canCancel, true);
    assert.equal((ownDetail.result.reservation as { memberFirstNameSnapshot: string }).memberFirstNameSnapshot, "花子");
    const ownPage = await fetch(`${origin}/account/reservations/${firstId}`, { headers: { cookie: memberCookie }, redirect: "manual" });
    assert.equal(ownPage.status, 200);
    assert((await ownPage.text()).includes("予約詳細"));
    const foreignPage = await fetch(`${origin}/account/reservations/${firstId}`, { headers: { cookie: otherCookie }, redirect: "manual" });
    assert.equal(foreignPage.status, 404);
    assert(!(await foreignPage.text()).includes("booking@example.test"));
    const anonymousPage = await fetch(`${origin}/account/reservations/${firstId}`, { redirect: "manual" });
    assert([302, 303, 307, 308].includes(anonymousPage.status));
    assert.equal(new URL(anonymousPage.headers.get("location")!, origin).pathname, "/login");
    assert.equal((await send("POST", "/api/reservations", firstBody)).result.replayed, true);
    assert.equal(await db.emailDelivery.count({ where: { reservationId: firstId } }), 2);
    assert.equal((await send("POST", "/api/reservations", { ...firstBody, startsAt: iso(date, 10) })).status, 409);
    const duplicateBody = create(14);
    const duplicates = await Promise.all([send("POST", "/api/reservations", duplicateBody), send("POST", "/api/reservations", duplicateBody)]);
    assert.deepEqual(duplicates.map(row => row.status), [201, 201]);
    assert.equal(duplicates[0].result.reservationId, duplicates[1].result.reservationId);
    const duplicateId = duplicates[0].result.reservationId as string;
    assert.equal(await db.emailDelivery.count({ where: { reservationId: duplicateId } }), 2);
    const duplicateCancelBody = { requestKey: randomUUID(), expectedVersion: 1 };
    const duplicateCancels = await Promise.all([send("DELETE", `/api/reservations/${duplicateId}`, duplicateCancelBody), send("DELETE", `/api/reservations/${duplicateId}`, duplicateCancelBody)]);
    assert.deepEqual(duplicateCancels.map(row => row.status), [200, 200]);
    assert.deepEqual(duplicateCancels.map(row => row.result.replayed).sort(), [false, true]);
    assert.equal(await db.emailDelivery.count({ where: { reservationId: duplicateId, kind: { in: ["RESERVATION_CANCELLED_MEMBER", "RESERVATION_CANCELLED_ADMIN"] } } }), 2);
    for (const stale of await db.emailDelivery.findMany({ where: { reservationId: duplicateId, kind: { in: ["RESERVATION_CONFIRMED_MEMBER", "RESERVATION_CONFIRMED_ADMIN"] } } })) {
      assert.equal((await runMailBatch(async () => { assert.fail("Cancelled reservation must not send confirmation"); }, 1, db, stale.id)).attempted, 0);
      assert.equal((await db.emailDelivery.findUniqueOrThrow({ where: { id: stale.id } })).status, "EXPIRED");
    }
    assert.deepEqual(duplicates.map(row => row.result.replayed).sort(), [false, true]);
    assert.equal((await send("PATCH", `/api/reservations/${firstId}`, { ...create(10), expectedVersion: 1 }, otherCookie)).status, 403);
    const changeBody = { ...create(10), expectedVersion: 1 };
    const changed = await send("PATCH", `/api/reservations/${firstId}`, changeBody);
    assert.equal(changed.status, 200, JSON.stringify(changed.result));
    assert.equal((await send("PATCH", `/api/reservations/${firstId}`, changeBody)).result.replayed, true);
    assert.equal((await send("PATCH", `/api/reservations/${firstId}`, { ...changeBody, requestKey: randomUUID() })).status, 409);
    assert.deepEqual((await db.reservationSlot.findMany({ where: { reservationId: firstId } })).map(row => row.slotStartsAt.toISOString()), [iso(date, 10)]);
    assert.equal((await send("DELETE", `/api/reservations/${firstId}`, { requestKey: randomUUID(), expectedVersion: 2 }, otherCookie)).status, 403);
    const cancelBody = { requestKey: randomUUID(), expectedVersion: 2, reason: "予定変更" };
    const beforeCancelDeliveries = await db.emailDelivery.count();
    await pg.query(`CREATE FUNCTION "${schema}".reject_cancel_admin_mail() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.kind = 'RESERVATION_CANCELLED_ADMIN' THEN RAISE EXCEPTION 'test rollback'; END IF; RETURN NEW; END $$`);
    await pg.query(`CREATE TRIGGER reject_cancel_admin_mail BEFORE INSERT ON "${schema}"."EmailDelivery" FOR EACH ROW EXECUTE FUNCTION "${schema}".reject_cancel_admin_mail()`);
    assert.equal((await send("DELETE", `/api/reservations/${firstId}`, cancelBody)).status, 503);
    assert.equal((await db.reservation.findUniqueOrThrow({ where: { id: firstId } })).status, "CONFIRMED");
    assert.equal((await db.reservation.findUniqueOrThrow({ where: { id: firstId } })).version, 2);
    assert.equal(await db.reservationSlot.count({ where: { reservationId: firstId } }), 1);
    assert.equal(await db.emailDelivery.count(), beforeCancelDeliveries);
    assert.equal(await db.auditLog.count({ where: { requestKey: cancelBody.requestKey } }), 0);
    await pg.query(`DROP TRIGGER reject_cancel_admin_mail ON "${schema}"."EmailDelivery"`);
    await pg.query(`DROP FUNCTION "${schema}".reject_cancel_admin_mail()`);
    const cancelled = await send("DELETE", `/api/reservations/${firstId}`, cancelBody);
    assert.equal(cancelled.status, 200, JSON.stringify(cancelled.result));
    assert.equal((await send("DELETE", `/api/reservations/${firstId}`, cancelBody)).result.replayed, true);
    const cancellationWhere = { reservationId: firstId, kind: { in: ["RESERVATION_CANCELLED_MEMBER", "RESERVATION_CANCELLED_ADMIN"] as ("RESERVATION_CANCELLED_MEMBER" | "RESERVATION_CANCELLED_ADMIN")[] } };
    const cancellationMails = await db.emailDelivery.findMany({ where: cancellationWhere });
    assert.equal(cancellationMails.length, 2);
    const cancelMemberMail = cancellationMails.find(row => row.kind === "RESERVATION_CANCELLED_MEMBER")!;
    const cancelAdminMail = cancellationMails.find(row => row.kind === "RESERVATION_CANCELLED_ADMIN")!;
    assert.equal(cancelMemberMail.reservationVersion, 3);
    const cancelPayload = decryptMailPayload(cancelMemberMail.encryptedPayload!);
    assert.equal(cancelPayload.to, member.email);
    assert.match(cancelPayload.subject, /キャンセルが完了/);
    assert.match(cancelPayload.text, /キャンセル日時/);
    assert(cancelPayload.text.includes(`${date.replaceAll("-", "/")} 10:00`));
    assert(cancelPayload.text.includes(`/account/reservations/${firstId}`));
    const cancelKeys: string[] = [];
    await runMailBatch(async (_payload, key) => { cancelKeys.push(key); return { kind: "TRANSIENT", code: "RATE_LIMITED" }; }, 1, db, cancelMemberMail.id);
    assert.equal((await db.emailDelivery.findUniqueOrThrow({ where: { id: cancelMemberMail.id } })).status, "RETRY_WAIT");
    await runMailBatch(async payload => { assert.equal(payload.to, process.env.ADMIN_EMAIL); assert.match(payload.subject, /会員が予約をキャンセル/); assert(payload.text.includes(`/manage/reservations/${firstId}`)); return { kind: "ACCEPTED" }; }, 1, db, cancelAdminMail.id);
    await db.emailDelivery.update({ where: { id: cancelMemberMail.id }, data: { nextAttemptAt: new Date() } });
    await runMailBatch(async (_payload, key) => { cancelKeys.push(key); return { kind: "ACCEPTED" }; }, 1, db, cancelMemberMail.id);
    assert.deepEqual(cancelKeys, [cancelMemberMail.requestKey, cancelMemberMail.requestKey]);
    assert.equal((await runMailBatch(async () => { assert.fail("Accepted cancellation must not send again"); }, 1, db, cancelMemberMail.id)).attempted, 0);
    assert.equal(await db.emailDelivery.count({ where: { ...cancellationWhere, status: "ACCEPTED", encryptedPayload: null } }), 2);

    assert.equal((await send("DELETE", `/api/reservations/${firstId}`, { requestKey: randomUUID(), expectedVersion: 2 })).status, 409);
    assert.equal(await db.emailDelivery.count({ where: cancellationWhere }), 2);
    assert.equal((await read(`/api/reservations/${firstId}`).then(row => row.result.reservation as { canCancel: boolean })).canCancel, false);
    assert.equal(await db.reservationSlot.count({ where: { reservationId: firstId } }), 0);
    const history = await db.reservation.findUniqueOrThrow({ where: { id: firstId } });
    assert.equal(history.status, "CANCELLED"); assert.equal(history.memberFirstNameSnapshot, "花子"); assert.equal(history.treatmentPriceYenSnapshot, 6000);
    const cancelledList = await storePage(`${storePath}&status=CANCELLED`, staffCookie);
    assert(cancelledList.html.includes(firstId));
    const cancelledCalendar = await storePage(`${storePath}&status=CANCELLED&view=calendar`, staffCookie);
    assert(cancelledCalendar.html.includes("表示する占有枠はありません"));
    const simultaneous = await Promise.all([send("POST", "/api/reservations", create(15)), send("POST", "/api/reservations", create(15))]);
    assert.deepEqual(simultaneous.map(row => row.status).sort(), [201, 409], JSON.stringify(simultaneous));
    assert.equal(await db.reservation.count({ where: { businessDate: parseBusinessDate(date), startsAt: new Date(iso(date, 15)), status: "CONFIRMED" } }), 1);
    const before = await db.reservation.count();
    const beforeOptions = await db.reservationOption.count();
    const beforeSlots = await db.reservationSlot.count();
    const beforeDeliveries = await db.emailDelivery.count();
    const secondSlot = iso(date, 17);
    await pg.query(`CREATE FUNCTION "${schema}".reject_second_slot() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW."slotStartsAt" = '${secondSlot}'::timestamptz THEN RAISE EXCEPTION 'test rollback'; END IF; RETURN NEW; END $$`);
    await pg.query(`CREATE TRIGGER reject_second_slot BEFORE INSERT ON "${schema}"."ReservationSlot" FOR EACH ROW EXECUTE FUNCTION "${schema}".reject_second_slot()`);
    const failed = await send("POST", "/api/reservations", create(16, [seedIds.options[0]]));
    assert.equal(failed.status, 503, JSON.stringify(failed.result));
    assert.equal(await db.reservation.count(), before);
    assert.equal(await db.reservationOption.count(), beforeOptions);
    assert.equal(await db.reservationSlot.count(), beforeSlots);
    assert.equal(await db.emailDelivery.count(), beforeDeliveries);
    await pg.query(`DROP TRIGGER reject_second_slot ON "${schema}"."ReservationSlot"`);
    await pg.query(`DROP FUNCTION "${schema}".reject_second_slot()`);
    await pg.query(`CREATE FUNCTION "${schema}".reject_admin_mail() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.kind = 'RESERVATION_CONFIRMED_ADMIN' THEN RAISE EXCEPTION 'test rollback'; END IF; RETURN NEW; END $$`);
    await pg.query(`CREATE TRIGGER reject_admin_mail BEFORE INSERT ON "${schema}"."EmailDelivery" FOR EACH ROW EXECUTE FUNCTION "${schema}".reject_admin_mail()`);
    const mailFailureBody = create(16);
    assert.equal((await send("POST", "/api/reservations", mailFailureBody)).status, 503);
    assert.equal(await db.reservation.count(), before);
    assert.equal(await db.reservationSlot.count(), beforeSlots);
    assert.equal(await db.emailDelivery.count(), beforeDeliveries);
    assert.equal(await db.auditLog.count({ where: { requestKey: mailFailureBody.requestKey } }), 0);
    await pg.query(`DROP TRIGGER reject_admin_mail ON "${schema}"."EmailDelivery"`);
    await pg.query(`DROP FUNCTION "${schema}".reject_admin_mail()`);
    const simultaneousId = simultaneous.find(row => row.status === 201)!.result.reservationId as string;
    const sameReservation = await Promise.all([
      send("PATCH", `/api/reservations/${simultaneousId}`, { ...create(16), expectedVersion: 1 }),
      send("DELETE", `/api/reservations/${simultaneousId}`, { requestKey: randomUUID(), expectedVersion: 1 }),
    ]);
    assert.deepEqual(sameReservation.map(row => row.status).sort(), [200, 409], JSON.stringify(sameReservation));
    const afterRace = await db.reservation.findUniqueOrThrow({ where: { id: simultaneousId }, include: { slots: true } });
    assert.equal(afterRace.version, 2);
    assert.equal(afterRace.slots.length, afterRace.status === "CANCELLED" ? 0 : 1);
    const settingDate = dayAfter(8);
    await pg.query("BEGIN");
    await pg.query(`SET LOCAL search_path TO "${schema}"`);
    await pg.query('SELECT id FROM "StoreSettingState" WHERE id=1 FOR UPDATE');
    const settingRequest = send("POST", "/api/reservations", { ...create(9), requestKey: randomUUID(), date: settingDate, startsAt: iso(settingDate, 9) });
    await new Promise(done => setTimeout(done, 250));
    const plan = randomUUID(), audit = randomUUID(), content = randomUUID();
    await pg.query('INSERT INTO "SchedulePlan" (id,kind,"effectiveDate") VALUES ($1,$2,$3)', [plan, "BUSINESS_DATE", settingDate]);
    await pg.query('INSERT INTO "AuditLog" (id,"requestKey","actorType",action,"targetType","targetId") VALUES ($1,$2,$3,$4,$5,$6)', [audit, randomUUID(), "SYSTEM", "test.setting", "SchedulePlan", plan]);
    await pg.query('INSERT INTO "BusinessDateOverride" (id,"isOpen","closesAt") VALUES ($1,false,$2)', [content, "18:00"]);
    await pg.query('INSERT INTO "ScheduleSettingChange" (id,"planId",revision,action,"auditId",reason,"businessOverrideId") VALUES ($1,$2,1,$3,$4,$5,$6)', [randomUUID(), plan, "CREATE", audit, "test closure", content]);
    await pg.query('UPDATE "StoreSettingState" SET version=version+1 WHERE id=1');
    await pg.query("COMMIT");
    assert.equal((await settingRequest).status, 409);
    assert.equal(await db.reservation.count({ where: { businessDate: parseBusinessDate(settingDate) } }), 0);
    const resourceDate = dayAfter(9);
    await pg.query("BEGIN");
    await pg.query(`SET LOCAL search_path TO "${schema}"`);
    await pg.query('SELECT id FROM "StoreSettingState" WHERE id=1 FOR UPDATE');
    const resourceRequest = send("POST", "/api/reservations", { ...create(9), date: resourceDate, startsAt: iso(resourceDate, 9) });
    await new Promise(done => setTimeout(done, 250));
    await pg.query('UPDATE "Room" SET "isActive"=false WHERE id=$1', [seedIds.rooms[0]]);
    await pg.query('UPDATE "StoreSettingState" SET version=version+1 WHERE id=1');
    await pg.query("COMMIT");
    assert.equal((await resourceRequest).status, 409);
    await db.room.update({ where: { id: seedIds.rooms[0] }, data: { isActive: true } });
    const catalogDate = dayAfter(10);
    await pg.query("BEGIN");
    await pg.query(`SET LOCAL search_path TO "${schema}"`);
    await pg.query('SELECT id FROM "Treatment" WHERE id=$1 FOR UPDATE', [seedIds.treatments[0]]);
    const catalogRequest = send("POST", "/api/reservations", { ...create(9), date: catalogDate, startsAt: iso(catalogDate, 9) });
    await new Promise(done => setTimeout(done, 250));
    await pg.query('UPDATE "Treatment" SET "isActive"=false WHERE id=$1', [seedIds.treatments[0]]);
    await pg.query("COMMIT");
    assert.equal((await catalogRequest).status, 409);
    await db.treatment.update({ where: { id: seedIds.treatments[0] }, data: { isActive: true } });
    const withdrawalDate = dayAfter(11);
    await pg.query("BEGIN");
    await pg.query(`SET LOCAL search_path TO "${schema}"`);
    await pg.query('SELECT id FROM "Member" WHERE id=$1 FOR UPDATE', [other.id]);
    const withdrawalRequest = send("POST", "/api/reservations", { ...create(9), date: withdrawalDate, startsAt: iso(withdrawalDate, 9) }, otherCookie);
    await new Promise(done => setTimeout(done, 250));
    await pg.query('UPDATE "Member" SET status=$1,"isDeleted"=true WHERE id=$2', ["WITHDRAWN", other.id]);
    await pg.query("COMMIT");
    assert([401, 403].includes((await withdrawalRequest).status));
    assert.equal(await db.reservation.count({ where: { memberId: other.id } }), 0);
    const pastDate = new Date(parseBusinessDate(tokyoBusinessDate(new Date())).getTime() - 86_400_000).toISOString().slice(0, 10);
    const pastId = randomUUID();
    await db.reservation.create({ data: { id: pastId, memberId: member.id, treatmentId: seedIds.treatments[0], roomId: seedIds.rooms[0], therapistId: seedIds.therapists[0], memberLastNameSnapshot: member.lastName, memberFirstNameSnapshot: member.firstName, memberEmailSnapshot: member.email, memberPhoneNumberSnapshot: member.phoneNumber, treatmentNameSnapshot: "ボディケア", treatmentDurationMinutesSnapshot: 60, treatmentPriceYenSnapshot: 6000, roomNameSnapshot: "施術ルーム1", therapistNameSnapshot: "施術者1", businessDate: parseBusinessDate(pastDate), startsAt: new Date(iso(pastDate, 9)), treatmentEndsAt: new Date(iso(pastDate, 10)), occupiesUntil: new Date(iso(pastDate, 10)), totalDurationMinutes: 60, totalPriceYen: 6000, slotCount: 1 } });
    await db.reservationSlot.create({ data: { reservationId: pastId, roomId: seedIds.rooms[0], therapistId: seedIds.therapists[0], slotStartsAt: new Date(iso(pastDate, 9)) } });
    assert.equal((await read(`/api/reservations/${pastId}`).then(row => row.result.reservation as { canCancel: boolean })).canCancel, false);
    assert.equal((await send("DELETE", `/api/reservations/${pastId}`, { requestKey: randomUUID(), expectedVersion: 1 })).status, 409);
    assert.equal((await send("DELETE", `/api/reservations/${pastId}`, { requestKey: randomUUID(), expectedVersion: 1, storeException: true }, adminCookie)).status, 400);
    assert.equal((await send("DELETE", `/api/reservations/${pastId}`, { requestKey: randomUUID(), expectedVersion: 1, storeException: true, exceptionReason: "店舗都合の中止" }, adminCookie)).status, 200);
    assert.equal(await db.reservationSlot.count({ where: { reservationId: pastId } }), 0);
    const pastChangeId = randomUUID();
    await db.reservation.create({ data: { id: pastChangeId, memberId: member.id, treatmentId: seedIds.treatments[0], roomId: seedIds.rooms[0], therapistId: seedIds.therapists[0], memberLastNameSnapshot: member.lastName, memberFirstNameSnapshot: member.firstName, memberEmailSnapshot: member.email, memberPhoneNumberSnapshot: member.phoneNumber, treatmentNameSnapshot: "ボディケア", treatmentDurationMinutesSnapshot: 60, treatmentPriceYenSnapshot: 6000, roomNameSnapshot: "施術ルーム1", therapistNameSnapshot: "施術者1", businessDate: parseBusinessDate(pastDate), startsAt: new Date(iso(pastDate, 11)), treatmentEndsAt: new Date(iso(pastDate, 12)), occupiesUntil: new Date(iso(pastDate, 12)), totalDurationMinutes: 60, totalPriceYen: 6000, slotCount: 1 } });
    await db.reservationSlot.create({ data: { reservationId: pastChangeId, roomId: seedIds.rooms[0], therapistId: seedIds.therapists[0], slotStartsAt: new Date(iso(pastDate, 11)) } });
    const changeDate = dayAfter(12);
    assert.equal((await send("PATCH", `/api/reservations/${pastChangeId}`, { ...create(9), date: changeDate, startsAt: iso(changeDate, 9), expectedVersion: 1 })).status, 409);
    const exceptionChange = await send("PATCH", `/api/reservations/${pastChangeId}`, { ...create(9), date: changeDate, startsAt: iso(changeDate, 9), expectedVersion: 1, storeException: true, exceptionReason: "店舗都合の移動" }, adminCookie);
    assert.equal(exceptionChange.status, 200, JSON.stringify(exceptionChange.result));
    assert.deepEqual((await db.reservationSlot.findMany({ where: { reservationId: pastChangeId } })).map(row => row.slotStartsAt.toISOString()), [iso(changeDate, 9)]);
    const memberSearchPath = "/api/manage/members?query=booking%40example.test";
    assert.equal((await fetch(`${origin}${memberSearchPath}`)).status, 401);
    assert.equal((await fetch(`${origin}${memberSearchPath}`, { headers: { cookie: memberCookie } })).status, 403);
    const memberSearch = await fetch(`${origin}${memberSearchPath}`, { headers: { cookie: staffCookie } });
    assert.equal(memberSearch.status, 200);
    assert((await memberSearch.json() as { members: { id: string; bookable: boolean }[] }).members.some(row => row.id === member.id && row.bookable));
    assert((await storePage("/manage/reservations/new", staffCookie)).html.includes("既存会員を選択"));
    assert(!(await storePage(`/manage/reservations/${pastChangeId}/edit`, staffCookie)).html.includes("空き時刻を検索"));
    await db.staffPermission.createMany({ data: (["RESERVATION_UPDATE", "RESERVATION_CANCEL", "RESERVATION_START", "RESERVATION_COMPLETE"] as const).map(permission => ({ staffId: staff.id, permission, grantedByAdminId: ADMIN_ID })) });
    await db.room.update({ where: { id: seedIds.rooms[1] }, data: { isActive: true } });
    await db.therapist.update({ where: { id: seedIds.therapists[1] }, data: { isActive: true } });
    const managedDate = dayAfter(14);
    const managedInput = { ...create(9), date: managedDate, startsAt: iso(managedDate, 9), memberId: member.id };
    const managedCreated = await send("POST", "/api/reservations", managedInput, staffCookie);
    assert.equal(managedCreated.status, 201, JSON.stringify(managedCreated.result));
    const managedId = managedCreated.result.reservationId as string;
    const managedEditPage = await storePage(`/manage/reservations/${managedId}/edit`, staffCookie);
    assert.equal(managedEditPage.status, 200);
    assert(managedEditPage.html.includes("予約を変更"));
    const previewParams = new URLSearchParams({ reservationId: managedId, date: managedDate, treatmentId: seedIds.treatments[0], roomId: seedIds.rooms[1], therapistId: seedIds.therapists[1] });
    previewParams.append("optionId", seedIds.options[0]);
    const previewResponse = await fetch(`${origin}/api/manage/availability?${previewParams}`, { headers: { cookie: staffCookie } });
    assert.equal(previewResponse.status, 200);
    assert((await previewResponse.json() as { times: { startsAt: string; roomId: string; therapistId: string }[] }).times.some(row => row.startsAt === iso(managedDate, 9) && row.roomId === seedIds.rooms[1] && row.therapistId === seedIds.therapists[1]));
    const assignedChange = { ...managedInput, requestKey: randomUUID(), expectedVersion: 1, optionIds: [seedIds.options[0]], quote: { totalDurationMinutes: 70, totalPriceYen: 7000 }, roomId: seedIds.rooms[1], therapistId: seedIds.therapists[1] };
    delete (assignedChange as { memberId?: string }).memberId;
    assert.equal((await send("PATCH", `/api/reservations/${managedId}`, assignedChange, memberCookie)).status, 403);
    const assigned = await send("PATCH", `/api/reservations/${managedId}`, assignedChange, staffCookie);
    assert.equal(assigned.status, 200, JSON.stringify(assigned.result));
    const savedAssignment = await db.reservation.findUniqueOrThrow({ where: { id: managedId } });
    assert.equal(savedAssignment.roomId, seedIds.rooms[1]);
    assert.equal(savedAssignment.therapistId, seedIds.therapists[1]);
    assert.deepEqual((await db.reservationSlot.findMany({ where: { reservationId: managedId }, orderBy: { slotStartsAt: "asc" } })).map(row => row.slotStartsAt.toISOString()), [iso(managedDate, 9), iso(managedDate, 10)]);
    const secondManaged = await send("POST", "/api/reservations", { ...managedInput, requestKey: randomUUID(), startsAt: iso(managedDate, 10) }, staffCookie);
    assert.equal(secondManaged.status, 201, JSON.stringify(secondManaged.result));
    const secondId = secondManaged.result.reservationId as string;
    const beforeSecond = await db.reservation.findUniqueOrThrow({ where: { id: secondId } });
    assert.equal((await send("PATCH", `/api/reservations/${secondId}`, { ...assignedChange, requestKey: randomUUID(), expectedVersion: 1, storeException: true, exceptionReason: "店舗都合の担当変更" }, staffCookie)).status, 403);
    const unavailableChange = await send("PATCH", `/api/reservations/${secondId}`, { ...assignedChange, requestKey: randomUUID(), expectedVersion: 1 }, staffCookie);
    assert.equal(unavailableChange.status, 409);
    assert.equal((await db.reservation.findUniqueOrThrow({ where: { id: secondId } })).version, 1);
    assert.equal((await db.reservation.findUniqueOrThrow({ where: { id: secondId } })).roomId, beforeSecond.roomId);
    const startBody = { requestKey: randomUUID(), expectedVersion: 2 };
    const progressPath = `/api/manage/reservations/${managedId}/progress?step=start`;
    const memberProgress = await send("POST", progressPath, startBody, memberCookie);
    assert.equal(memberProgress.status, 403, JSON.stringify(memberProgress.result));
    const started = await send("POST", progressPath, startBody, staffCookie);
    assert.equal(started.status, 200, JSON.stringify(started.result));
    assert.equal((await send("POST", progressPath, startBody, staffCookie)).result.replayed, true);
    assert.equal((await send("POST", progressPath, { requestKey: randomUUID(), expectedVersion: 2 }, staffCookie)).status, 409);
    const complete = await send("POST", `/api/manage/reservations/${managedId}/progress?step=complete`, { requestKey: randomUUID(), expectedVersion: 3 }, staffCookie);
    assert.equal(complete.status, 200, JSON.stringify(complete.result));
    const completed = await db.reservation.findUniqueOrThrow({ where: { id: managedId } });
    assert.equal(completed.status, "COMPLETED");
    assert(completed.actualStartedAt && completed.actualCompletedAt && completed.actualCompletedAt >= completed.actualStartedAt);
    assert.equal(await db.reservationSlot.count({ where: { reservationId: managedId } }), 2);
    assert.equal((await send("DELETE", `/api/reservations/${managedId}`, { requestKey: randomUUID(), expectedVersion: 4 }, staffCookie)).status, 409);
    const raceBody = { ...managedInput, requestKey: randomUUID(), expectedVersion: 1, startsAt: iso(managedDate, 11) };
    delete (raceBody as { memberId?: string }).memberId;
    const staffRace = await Promise.all([send("PATCH", `/api/reservations/${secondId}`, raceBody, staffCookie), send("DELETE", `/api/reservations/${secondId}`, { requestKey: randomUUID(), expectedVersion: 1 }, staffCookie)]);
    assert.deepEqual(staffRace.map(row => row.status).sort(), [200, 409], JSON.stringify(staffRace));
    assert.equal((await db.reservation.findUniqueOrThrow({ where: { id: secondId } })).version, 2);
    const beforeSettingDate = dayAfter(17);
    const beforeSetting = await send("POST", "/api/reservations", { ...create(9), date: beforeSettingDate, startsAt: iso(beforeSettingDate, 9), memberId: member.id }, staffCookie);
    assert.equal(beforeSetting.status, 201, JSON.stringify(beforeSetting.result));
    const beforeSettingId = beforeSetting.result.reservationId as string;
    const oldAssignment = await db.reservation.findUniqueOrThrow({ where: { id: beforeSettingId } });
    assert.equal(oldAssignment.therapistId, seedIds.therapists[0]);
    const movedBeforeSetting = await send("PATCH", `/api/reservations/${beforeSettingId}`, { ...create(9), date: beforeSettingDate, startsAt: iso(beforeSettingDate, 9), expectedVersion: 1, roomId: seedIds.rooms[1], therapistId: seedIds.therapists[1] }, staffCookie);
    assert.equal(movedBeforeSetting.status, 200, JSON.stringify(movedBeforeSetting.result));
    const oldTherapist = await db.therapist.findUniqueOrThrow({ where: { id: seedIds.therapists[0] } });
    const disabledPath = `/api/manage/resources/therapists/${oldTherapist.id}`;
    const previewDisable = await send("PATCH", disabledPath, { operation: "preview-disable", updatedAt: oldTherapist.updatedAt.toISOString() }, adminCookie);
    assert.equal(previewDisable.status, 200, JSON.stringify(previewDisable.result));
    assert(!(previewDisable.result.affected as { reservationId: string }[]).some(row => row.reservationId === beforeSettingId));
    const disabled = await send("PATCH", disabledPath, { operation: "disable", updatedAt: oldTherapist.updatedAt.toISOString(), reviewToken: previewDisable.result.reviewToken }, adminCookie);
    assert.equal(disabled.status, 200, JSON.stringify(disabled.result));
    assert.equal(await db.reservationChangeNotice.count({ where: { reservationId: beforeSettingId } }), 0);
    assert.equal((await db.reservation.findUniqueOrThrow({ where: { id: beforeSettingId } })).therapistId, seedIds.therapists[1]);
    const sourceAudit = await db.auditLog.create({ data: { requestKey: randomUUID(), actorType: "ADMIN", actorAdminId: ADMIN_ID, action: "TEST_SETTING_CHANGE", targetType: "Reservation", targetId: beforeSettingId, changes: { source: "isolated-test" } } });
    const adjustment = await db.reservationChangeNotice.create({ data: { reservationId: beforeSettingId, changeAuditId: sourceAudit.id, reservationVersion: 2, reason: "RESOURCE_UNAVAILABLE" } });
    const candidatePath = `/api/manage/adjustments/${adjustment.id}/candidates`;
    assert.equal((await fetch(`${origin}${candidatePath}`, { headers: { cookie: memberCookie } })).status, 403);
    const candidatesResponse = await fetch(`${origin}${candidatePath}`, { headers: { cookie: staffCookie } });
    assert.equal(candidatesResponse.status, 200, `${adjustment.id}: ${await candidatesResponse.clone().text()}`);
    const candidates = (await candidatesResponse.json() as { candidates: { startsAt: string }[] }).candidates;
    assert(candidates.length > 0);
    assert(candidates.every(row => row.startsAt.slice(0, 10) === iso(beforeSettingDate, 9).slice(0, 10) && Math.abs(Date.parse(row.startsAt) - Date.parse(iso(beforeSettingDate, 9))) <= 2 * 60 * 60_000));
    const adjustmentPage = await storePage(`/manage/adjustments/${adjustment.id}`, staffCookie);
    assert.equal(adjustmentPage.status, 200);
    assert(adjustmentPage.html.includes("候補は仮押さえではありません"));
    await db.treatment.update({ where: { id: seedIds.treatments[0] }, data: { isActive: false } });
    const noCandidates = await fetch(`${origin}${candidatePath}`, { headers: { cookie: staffCookie } });
    assert.deepEqual((await noCandidates.json() as { candidates: unknown[] }).candidates, []);
    await db.treatment.update({ where: { id: seedIds.treatments[0] }, data: { isActive: true } });
    const noticeSendPath = `/api/manage/adjustments/${adjustment.id}/send`;
    assert.equal((await send("POST", noticeSendPath, { expectedVersion: 1, confirmed: true }, staffCookie)).status, 403);
    const sent = await send("POST", noticeSendPath, { expectedVersion: 1, confirmed: true }, adminCookie);
    assert.equal(sent.status, 200, JSON.stringify(sent.result));
    assert.equal((await send("POST", noticeSendPath, { expectedVersion: 1, confirmed: true }, adminCookie)).status, 200);
    assert.equal(await db.emailDelivery.count({ where: { noticeId: adjustment.id } }), 1);
    const keys: string[] = [];
    const noticeDelivery = await db.emailDelivery.findFirstOrThrow({ where: { noticeId: adjustment.id } });
    const firstMail = await runMailBatch(async (payload, key) => { keys.push(key); assert.match(payload.text, /候補時刻/); assert.match(payload.text, /店舗までご連絡/); return { kind: "TRANSIENT", code: "RATE_LIMITED" }; }, 1, db, noticeDelivery.id);
    assert.equal(firstMail.attempted, 1);
    const delivery = await db.emailDelivery.findFirstOrThrow({ where: { noticeId: adjustment.id } });
    assert.equal(delivery.status, "RETRY_WAIT");
    await db.emailDelivery.update({ where: { id: delivery.id }, data: { nextAttemptAt: new Date() } });
    const retryMail = await runMailBatch(async (_payload, key) => { keys.push(key); return { kind: "ACCEPTED" }; }, 1, db, delivery.id);
    assert.equal(retryMail.attempted, 1);
    assert.deepEqual(keys, [delivery.requestKey, delivery.requestKey]);
    assert.equal(await db.emailDeliveryAttempt.count({ where: { deliveryId: delivery.id } }), 2);
    const responsePath = `/api/manage/adjustments/${adjustment.id}/response`;
    const awaiting = { requestKey: randomUUID(), expectedVersion: 1, status: "AWAITING_CUSTOMER", note: "電話で候補を案内し返信待ち" };
    assert.equal((await send("POST", responsePath, awaiting, staffCookie)).status, 403);
    await db.staffPermission.create({ data: { staffId: staff.id, permission: "NOTICE_UPDATE_RESPONSE", grantedByAdminId: ADMIN_ID } });
    assert.equal((await send("POST", responsePath, { ...awaiting, expectedVersion: 2 }, staffCookie)).status, 409);
    assert.equal((await send("POST", responsePath, awaiting, staffCookie)).status, 200);
    assert.equal((await send("POST", responsePath, awaiting, staffCookie)).result.replayed, true);
    assert.equal((await db.reservationChangeNotice.findUniqueOrThrow({ where: { id: adjustment.id } })).responseStatus, "AWAITING_CUSTOMER");
    assert.equal((await send("POST", responsePath, { requestKey: randomUUID(), expectedVersion: 2, status: "RESOLVED", note: "未対応なのに完了" }, staffCookie)).status, 409);
    assert.equal((await send("POST", responsePath, { requestKey: randomUUID(), expectedVersion: 2, status: "IN_PROGRESS", note: "変更希望を受付" }, staffCookie)).status, 200);
    const occupied = await send("POST", "/api/reservations", { ...create(10), date: beforeSettingDate, startsAt: iso(beforeSettingDate, 10), memberId: member.id }, staffCookie);
    assert.equal(occupied.status, 201, JSON.stringify(occupied.result));
    const staleCandidate = await send("PATCH", `/api/reservations/${beforeSettingId}`, { ...create(10), date: beforeSettingDate, startsAt: iso(beforeSettingDate, 10), expectedVersion: 2 }, staffCookie);
    assert.equal(staleCandidate.status, 409);
    assert.equal((await db.reservation.findUniqueOrThrow({ where: { id: beforeSettingId } })).version, 2);
    assert.equal((await db.reservationChangeNotice.findUniqueOrThrow({ where: { id: adjustment.id } })).responseStatus, "IN_PROGRESS");
    assert.equal((await send("PATCH", `/api/reservations/${beforeSettingId}`, { ...create(11), date: beforeSettingDate, startsAt: iso(beforeSettingDate, 11), expectedVersion: 2, storeException: true, exceptionReason: "顧客の依頼による店舗都合の変更" }, staffCookie)).status, 403);
    await db.staffPermission.create({ data: { staffId: staff.id, permission: "RESERVATION_EXCEPTION", grantedByAdminId: ADMIN_ID } });
    const adjusted = await send("PATCH", `/api/reservations/${beforeSettingId}`, { ...create(11), date: beforeSettingDate, startsAt: iso(beforeSettingDate, 11), expectedVersion: 2, storeException: true, exceptionReason: "顧客の依頼による店舗都合の変更" }, staffCookie);
    assert.equal(adjusted.status, 200, JSON.stringify(adjusted.result));
    const resolvedAdjustment = await db.reservationChangeNotice.findUniqueOrThrow({ where: { id: adjustment.id } });
    assert.equal(resolvedAdjustment.responseStatus, "RESOLVED"); assert(resolvedAdjustment.resolvedAt);
    assert.equal((await db.reservation.findUniqueOrThrow({ where: { id: beforeSettingId } })).startsAt.toISOString(), iso(beforeSettingDate, 11));
    assert.equal(await db.reservationChangeNotice.count({ where: { id: adjustment.id } }), 1);
    const noCandidateReservation = occupied.result.reservationId as string;
    const noCandidateAudit = await db.auditLog.create({ data: { requestKey: randomUUID(), actorType: "ADMIN", actorAdminId: ADMIN_ID, action: "TEST_SETTING_CHANGE", targetType: "Reservation", targetId: noCandidateReservation, changes: { source: "isolated-test" } } });
    const noCandidateNotice = await db.reservationChangeNotice.create({ data: { reservationId: noCandidateReservation, changeAuditId: noCandidateAudit.id, reservationVersion: 1, reason: "RESOURCE_UNAVAILABLE" } });
    await db.treatment.update({ where: { id: seedIds.treatments[0] }, data: { isActive: false } });
    assert.equal((await send("POST", `/api/manage/adjustments/${noCandidateNotice.id}/send`, { expectedVersion: 1, confirmed: true }, adminCookie)).status, 200);
    const emptyDelivery = await db.emailDelivery.findFirstOrThrow({ where: { noticeId: noCandidateNotice.id } });
    const emptyMail = await runMailBatch(async payload => { assert.match(payload.text, /空き候補がありません/); assert.match(payload.text, /店舗までご連絡/); return { kind: "ACCEPTED" }; }, 1, db, emptyDelivery.id);
    assert.equal(emptyMail.attempted, 1);
    await db.treatment.update({ where: { id: seedIds.treatments[0] }, data: { isActive: true } });
    assert.equal((await db.reservationChangeNotice.findUniqueOrThrow({ where: { id: noCandidateNotice.id } })).responseStatus, "UNCONTACTED");
    assert.equal((await db.reservation.findUniqueOrThrow({ where: { id: noCandidateReservation } })).status, "CONFIRMED");
    const cancelledAdjustment = await send("DELETE", `/api/reservations/${noCandidateReservation}`, { requestKey: randomUUID(), expectedVersion: 1, storeException: true, exceptionReason: "顧客と相談し店舗都合で取消" }, staffCookie);
    assert.equal(cancelledAdjustment.status, 200, JSON.stringify(cancelledAdjustment.result));
    assert.equal((await db.reservationChangeNotice.findUniqueOrThrow({ where: { id: noCandidateNotice.id } })).responseStatus, "RESOLVED");
    assert.equal(await db.reservationSlot.count({ where: { reservationId: noCandidateReservation } }), 0);
    assert.equal(await db.emailDelivery.count({ where: { reservationId: noCandidateReservation, kind: { in: ["RESERVATION_CANCELLED_MEMBER", "RESERVATION_CANCELLED_ADMIN"] } } }), 0);
    const reviewAudit = await db.auditLog.create({ data: { requestKey: randomUUID(), actorType: "ADMIN", actorAdminId: ADMIN_ID, action: "TEST_SETTING_CHANGE", targetType: "Reservation", targetId: beforeSettingId, changes: { source: "isolated-test" } } });
    const pendingReview = await db.reservationChangeNotice.create({ data: { reservationId: beforeSettingId, changeAuditId: reviewAudit.id, reservationVersion: 3, reason: "RESOURCE_UNAVAILABLE", responseStatus: "IMPACT_RESOLVED_PENDING_REVIEW" } });
    assert.equal((await send("POST", `/api/manage/adjustments/${pendingReview.id}/response`, { requestKey: randomUUID(), expectedVersion: 1, status: "RESOLVED", note: "設定再変更による影響解消を確認" }, staffCookie)).status, 200);
    assert.equal((await db.reservationChangeNotice.findUniqueOrThrow({ where: { id: pendingReview.id } })).responseStatus, "RESOLVED");
    process.stdout.write("Booking HTTP and isolated PostgreSQL concurrency, rollback, setting, ownership and history checks passed.\n");
  } finally {
    if (server) { server.kill("SIGTERM"); await once(server, "exit").catch(() => {}); }
    await db?.$disconnect();
    rmSync(distDir, { recursive: true, force: true });
    await pg.query("ROLLBACK").catch(() => {});
    await pg.query(`DROP SCHEMA IF EXISTS "${schema}" CASCADE`);
    await pg.end();
  }
}
main().catch((error: unknown) => {
  // Assertion messages can contain response bodies, tokens and member snapshots.
  if (error instanceof Error) process.stderr.write(`${error.name}\n${error.stack?.split("\n").filter(line => line.trim().startsWith("at ")).join("\n") ?? ""}\n`);
  process.stderr.write("Integration failed; inspect assertions locally without logging response bodies.\n");
  process.exitCode = 1;
});
