import assert from "node:assert/strict";
import { randomBytes, randomUUID, createHash } from "node:crypto";
import { spawn, type ChildProcess } from "node:child_process";
import { createServer } from "node:net";
import { once } from "node:events";
import { mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { Client } from "pg";
import { PrismaPg } from "@prisma/adapter-pg";
import { PrismaClient } from "../src/generated/prisma/client";
import { loadDevelopmentDatabase, runPrisma } from "./lib/development-database";
import { seedDevelopment, seedIds } from "../prisma/seed-data";
import { parseBusinessDate, tokyoBusinessDate } from "../src/lib/schedules/calendar";
import { tokyoInstant } from "../src/lib/booking/availability-core";
import { ADMIN_ID } from "../src/lib/auth/policy";
import { encode } from "next-auth/jwt";

const iso = (date: string, hour: number) => new Date(tokyoInstant(date, hour)).toISOString();
function dayAfter(days: number) {
  const date = new Date(parseBusinessDate(tokyoBusinessDate(new Date())).getTime() + days * 86_400_000);
  while (date.getUTCDay() === 0) date.setUTCDate(date.getUTCDate() + 1);
  return date.toISOString().slice(0, 10);
}

async function main() {
  const connectionString = loadDevelopmentDatabase();
  const schema = `withdraw_verify_${randomUUID().replaceAll("-", "")}`;
  const pg = new Client({ connectionString }); await pg.connect();
  const distDir = `.next-withdraw-test-${schema}`;
  let db: PrismaClient | undefined;
  let server: ChildProcess | undefined;
  try {
    await pg.query(`CREATE SCHEMA "${schema}"`);
    const url = new URL(connectionString); url.searchParams.set("schema", schema);
    runPrisma(["migrate", "deploy"], url.href);
    process.env.DATABASE_URL = url.href;
    db = new PrismaClient({ adapter: new PrismaPg({ connectionString }, { schema }), log: [] });
    await seedDevelopment(db);
    const member = await db.member.create({ data: { email: "withdraw@example.test", emailKey: "withdraw@example.test", lastName: "退会", firstName: "花子", lastNameKey: "退会", firstNameKey: "花子", phoneNumber: "09012345678", postalCode: "0010000", ageBand: 30, passwordHash: "test-only-not-a-login-hash", status: "ACTIVE", emailVerifiedAt: new Date(), firstActivatedAt: new Date() } });
    const forced = await db.member.create({ data: { email: "forced@example.test", emailKey: "forced@example.test", lastName: "強制", firstName: "太郎", lastNameKey: "強制", firstNameKey: "太郎", phoneNumber: "09011112222", postalCode: "0010000", ageBand: 30, passwordHash: "test-only-not-a-login-hash", status: "ACTIVE", emailVerifiedAt: new Date(), firstActivatedAt: new Date() } });
    const racing = await db.member.create({ data: { email: "racing@example.test", emailKey: "racing@example.test", lastName: "競合", firstName: "会員", lastNameKey: "競合", firstNameKey: "会員", phoneNumber: "09033334444", postalCode: "0010000", ageBand: 30, passwordHash: "test-only-not-a-login-hash", status: "ACTIVE", emailVerifiedAt: new Date(), firstActivatedAt: new Date() } });
    const rollbackMember = await db.member.create({ data: { email: "rollback@example.test", emailKey: "rollback@example.test", lastName: "失敗", firstName: "確認", lastNameKey: "失敗", firstNameKey: "確認", phoneNumber: "09077778888", postalCode: "0010000", ageBand: 30, passwordHash: "test-only-not-a-login-hash", status: "ACTIVE", emailVerifiedAt: new Date(), firstActivatedAt: new Date() } });
    const doubleMember = await db.member.create({ data: { email: "double@example.test", emailKey: "double@example.test", lastName: "二重", firstName: "操作", lastNameKey: "二重", firstNameKey: "操作", phoneNumber: "09099990000", postalCode: "0010000", ageBand: 30, passwordHash: "test-only-not-a-login-hash", status: "ACTIVE", emailVerifiedAt: new Date(), firstActivatedAt: new Date() } });
    const staff = await db.staffAccount.create({ data: { email: "withdraw-staff@example.test", emailKey: "withdraw-staff@example.test", displayName: "退会担当", passwordHash: "test-only-not-a-login-hash" } });
    const portProbe = createServer(); portProbe.listen(0, "127.0.0.1"); await once(portProbe, "listening");
    const port = (portProbe.address() as { port: number }).port;
    await new Promise<void>(done => portProbe.close(() => done()));
    const origin = `http://127.0.0.1:${port}`;
    process.env.AUTH_URL = origin;
    process.env.AUTH_SECRET = randomBytes(32).toString("hex");
    process.env.AUTH_RATE_LIMIT_SECRET = randomBytes(32).toString("hex");
    process.env.MAIL_PAYLOAD_KEY = randomBytes(32).toString("base64");
    process.env.RESEND_FROM = "mail@example.test";
    process.env.RESEND_API_KEY = "re_test_local_only";
    process.env.MAIL_TEST_DISABLE_IMMEDIATE = "1";
    process.env.ADMIN_EMAIL = "admin@example.test";
    process.env.ADMIN_PASSWORD = randomBytes(24).toString("base64url");
    process.env.ADMIN_AUTH_VERSION = "1";
    mkdirSync(distDir);
    const tsconfig = JSON.parse(readFileSync("tsconfig.json", "utf8"));
    tsconfig.include = [resolve("src/**/*.ts"), resolve("src/**/*.tsx"), resolve("next-env.d.ts")];
    tsconfig.compilerOptions.baseUrl = process.cwd();
    tsconfig.compilerOptions.paths = { "@/*": ["./src/*"] };
    writeFileSync(`${distDir}/tsconfig.json`, JSON.stringify(tsconfig));
    server = spawn(process.execPath, ["node_modules/next/dist/bin/next", "dev", "--webpack", "-p", String(port), "-H", "127.0.0.1"], { env: { ...process.env, NODE_OPTIONS: "", NEXT_DIST_DIR: distDir, AUTH_TEST_TSCONFIG: `${distDir}/tsconfig.json` }, stdio: ["ignore", "pipe", "pipe"] });
    let output = ""; server.stdout?.on("data", part => { output = (output + String(part)).slice(-8000); }); server.stderr?.on("data", part => { output = (output + String(part)).slice(-8000); });
    let ready = false;
    for (let i = 0; i < 90; i++) { try { if ((await fetch(`${origin}/api/auth/csrf`)).ok) { ready = true; break; } } catch {} if (server.exitCode !== null) break; await new Promise(done => setTimeout(done, 500)); }
    if (!ready) process.stderr.write(output.replaceAll(process.env.ADMIN_PASSWORD!, "[redacted]"));
    assert(ready, "Test server did not become ready.");
    async function cookie(role: "MEMBER" | "STAFF" | "ADMIN", principalId: string, version = 1) {
      const expiresAt = new Date(Date.now() + 60 * 60_000);
      const session = await db!.appSession.create({ data: { principalType: role, ...(role === "MEMBER" ? { memberId: principalId } : role === "STAFF" ? { staffId: principalId } : { adminId: principalId }), authVersion: version, expiresAt } });
      const token = await encode({ token: { sid: session.id, principalId, role, authVersion: version, absoluteExpiry: expiresAt.getTime() }, secret: process.env.AUTH_SECRET!, salt: "authjs.session-token", maxAge: 3600 });
      return `authjs.session-token=${token}`;
    }
    const memberCookie = await cookie("MEMBER", member.id);
    const forcedCookie = await cookie("MEMBER", forced.id);
    const raceCookie = await cookie("MEMBER", racing.id);
    const rollbackCookie = await cookie("MEMBER", rollbackMember.id);
    const doubleCookie = await cookie("MEMBER", doubleMember.id);
    const adminCookie = await cookie("ADMIN", ADMIN_ID);
    const staffCookie = await cookie("STAFF", staff.id);
    async function send(path: string, body: object, session = memberCookie) {
      const response = await fetch(`${origin}${path}`, { method: "POST", headers: { origin, cookie: session, "content-type": "application/json" }, body: JSON.stringify(body) });
      return { status: response.status, result: await response.json() as Record<string, unknown>, setCookie: response.headers.get("set-cookie") };
    }
    async function preview(session = memberCookie) {
      const response = await fetch(`${origin}/api/member/withdraw/preview`, { headers: { cookie: session } });
      return { status: response.status, result: await response.json() as { preview?: { expectedVersion: number; reviewToken: string; confirmed: { id: string }[] } } };
    }
    const date = dayAfter(7);
    const booking = (hour: number, targetDate = date, options: string[] = []) => ({ requestKey: randomUUID(), date: targetDate, startsAt: iso(targetDate, hour), treatmentId: seedIds.treatments[0], optionIds: options, quote: { totalDurationMinutes: options.length ? 70 : 60, totalPriceYen: options.length ? 7000 : 6000 } });
    const confirmed = await send("/api/reservations", booking(9, date, [seedIds.options[0]]));
    assert.equal(confirmed.status, 201, JSON.stringify(confirmed.result));
    const confirmedId = confirmed.result.reservationId as string;
    assert.equal(await db.reservationSlot.count({ where: { reservationId: confirmedId } }), 2);
    const forcedBooking = await send("/api/reservations", booking(12), forcedCookie);
    assert.equal(forcedBooking.status, 201, JSON.stringify(forcedBooking.result));
    const forcedReservationId = forcedBooking.result.reservationId as string;
    const previouslyCancelled = await send("/api/reservations", booking(14));
    assert.equal(previouslyCancelled.status, 201);
    const cancelledId = previouslyCancelled.result.reservationId as string;
    assert.equal((await preview("")).status, 401);
    const withdrawalPage = await fetch(`${origin}/account/withdraw`, { headers: { cookie: memberCookie }, redirect: "manual" });
    assert.equal(withdrawalPage.status, 200);
    assert((await withdrawalPage.text()).includes("退会手続き"));
    const anonymousPage = await fetch(`${origin}/account/withdraw`, { redirect: "manual" });
    assert([302, 303, 307, 308].includes(anonymousPage.status));
    assert.equal(new URL(anonymousPage.headers.get("location")!, origin).pathname, "/login");
    const stalePreview = await preview();
    assert.equal(stalePreview.status, 200);
    assert(stalePreview.result.preview!.confirmed.some(row => row.id === cancelledId));
    const cancelledResponse = await fetch(`${origin}/api/reservations/${cancelledId}`, { method: "DELETE", headers: { origin, cookie: memberCookie, "content-type": "application/json" }, body: JSON.stringify({ requestKey: randomUUID(), expectedVersion: 1 }) });
    assert.equal(cancelledResponse.status, 200);
    const pastDate = new Date(parseBusinessDate(tokyoBusinessDate(new Date())).getTime() - 86_400_000).toISOString().slice(0, 10);
    async function historical(status: "CONFIRMED" | "IN_PROGRESS" | "COMPLETED", hour: number) {
      const id = randomUUID(), startsAt = new Date(iso(pastDate, hour)), endsAt = new Date(iso(pastDate, hour + 1));
      await db!.reservation.create({ data: { id, memberId: member.id, treatmentId: seedIds.treatments[0], roomId: seedIds.rooms[0], therapistId: seedIds.therapists[0], memberLastNameSnapshot: member.lastName, memberFirstNameSnapshot: member.firstName, memberEmailSnapshot: member.email, memberPhoneNumberSnapshot: member.phoneNumber, treatmentNameSnapshot: "ボディケア", treatmentDurationMinutesSnapshot: 60, treatmentPriceYenSnapshot: 6000, roomNameSnapshot: "施術ルーム1", therapistNameSnapshot: "施術者1", status, businessDate: parseBusinessDate(pastDate), startsAt, treatmentEndsAt: endsAt, occupiesUntil: endsAt, totalDurationMinutes: 60, totalPriceYen: 6000, slotCount: 1, ...(status === "IN_PROGRESS" ? { actualStartedAt: startsAt } : status === "COMPLETED" ? { actualStartedAt: startsAt, actualCompletedAt: endsAt } : {}) } });
      await db!.reservationSlot.create({ data: { reservationId: id, roomId: seedIds.rooms[0], therapistId: seedIds.therapists[0], slotStartsAt: startsAt } });
      return id;
    }
    const pastConfirmedId = await historical("CONFIRMED", 9);
    const ongoingId = await historical("IN_PROGRESS", 10);
    const completedId = await historical("COMPLETED", 11);
    const testToken = await db.authToken.create({ data: { digest: createHash("sha256").update(randomUUID()).digest("hex"), purpose: "PASSWORD_RESET", memberId: member.id, emailKey: member.emailKey, authVersion: 1, expiresAt: new Date(Date.now() + 60 * 60_000) } });
    assert.equal((await send("/api/member/withdraw", { requestKey: randomUUID(), expectedVersion: 1, reviewToken: stalePreview.result.preview!.reviewToken, reason: "古い確認" })).status, 409);
    assert.equal((await db.member.findUniqueOrThrow({ where: { id: member.id } })).status, "ACTIVE");
    const currentPreview = await preview();
    assert.equal(currentPreview.status, 200);
    assert.equal(currentPreview.result.preview!.expectedVersion, 1);
    assert.equal(currentPreview.result.preview!.confirmed.length, 2);
    assert.equal((await send("/api/member/withdraw", { requestKey: randomUUID(), expectedVersion: 1, reason: " " })).status, 400);
    assert.equal((await send("/api/member/withdraw", { requestKey: randomUUID(), expectedVersion: 1, reason: "退会希望" }, "")).status, 401);
    assert.equal((await send("/api/member/withdraw", { requestKey: randomUUID(), expectedVersion: 1, reason: "退会希望" }, staffCookie)).status, 403);
    assert.equal((await send("/api/member/withdraw", { requestKey: randomUUID(), expectedVersion: 1, reason: "退会希望", memberId: forced.id })).status, 400);
    const withdrawal = await send("/api/member/withdraw", { requestKey: randomUUID(), expectedVersion: 1, reviewToken: currentPreview.result.preview!.reviewToken, reason: "退会希望" });
    assert.equal(withdrawal.status, 200, JSON.stringify(withdrawal.result));
    assert(withdrawal.setCookie?.includes("authjs.session-token=; Max-Age=0"));
    assert.equal(withdrawal.result.cancelledCount, 2);
    assert.equal((await preview()).status, 401);
    const withdrawnPage = await fetch(`${origin}/account/withdraw`, { headers: { cookie: memberCookie }, redirect: "manual" });
    assert([302, 303, 307, 308].includes(withdrawnPage.status));
    const inactive = await db.member.findUniqueOrThrow({ where: { id: member.id } });
    assert.equal(inactive.status, "WITHDRAWN"); assert.equal(inactive.isDeleted, true); assert.equal(inactive.version, 2);
    assert.equal((await db.memberLifecycleEvent.findFirstOrThrow({ where: { memberId: member.id, kind: "VOLUNTARY_WITHDRAWAL" } })).reason, "退会希望");
    for (const id of [confirmedId, pastConfirmedId]) {
      const reservation: { status: string; cancellationKind: string | null } = await db.reservation.findUniqueOrThrow({ where: { id } });
      assert.equal(reservation.status, "CANCELLED"); assert.equal(reservation.cancellationKind, "MEMBER_WITHDRAWAL");
      assert.equal(await db.reservationSlot.count({ where: { reservationId: id } }), 0);
    }
    assert.equal(await db.reservationOption.count({ where: { reservationId: confirmedId } }), 1);
    for (const id of [ongoingId, completedId]) assert.equal(await db.reservationSlot.count({ where: { reservationId: id } }), 1);
    assert.equal((await db.reservation.findUniqueOrThrow({ where: { id: cancelledId } })).status, "CANCELLED");
    assert((await db.authToken.findUniqueOrThrow({ where: { id: testToken.id } })).revokedAt);
    assert.equal(await db.appSession.count({ where: { memberId: member.id, revokedAt: null } }), 0);
    assert.equal((await send("/api/reservations", booking(16))).status, 401);
    assert.equal((await send("/api/member/withdraw", { requestKey: randomUUID(), expectedVersion: 1, reason: "再送" })).status, 401);
    const restore = await send(`/api/manage/members/${member.id}/restore`, { expectedVersion: 2, reason: "本人確認後に復旧" }, adminCookie);
    assert.equal(restore.status, 200, JSON.stringify(restore.result));
    assert.equal((await db.member.findUniqueOrThrow({ where: { id: member.id } })).status, "RESTORE_PENDING");
    assert.equal((await send("/api/reservations", { ...booking(16), memberId: member.id }, adminCookie)).status, 403);
    const delivery = await db.emailDelivery.findFirstOrThrow({ where: { recipient: member.email, kind: "RESTORE_CONFIRM", encryptedPayload: { not: null } }, orderBy: { createdAt: "desc" } });
    const { decryptMailPayload } = await import("../src/lib/member/mail");
    const restoreToken = decryptMailPayload(delivery.encryptedPayload!).text.match(/#token=([A-Za-z0-9_-]{43})/)?.[1];
    assert(restoreToken);
    const restored = await send("/api/member/restore", { token: restoreToken, password: "new-password-for-restore-123" }, "");
    assert.equal(restored.status, 200, JSON.stringify(restored.result));
    const activeAgain = await db.member.findUniqueOrThrow({ where: { id: member.id } });
    assert.equal(activeAgain.status, "ACTIVE"); assert.equal(activeAgain.isDeleted, false);
    assert.equal(await db.reservationSlot.count({ where: { reservationId: confirmedId } }), 0);
    assert.equal((await db.reservation.findUniqueOrThrow({ where: { id: confirmedId } })).status, "CANCELLED");
    assert.equal(await db.reservationSlot.count({ where: { reservationId: ongoingId } }), 1);
    assert.equal(await db.reservationSlot.count({ where: { reservationId: completedId } }), 1);
    assert.equal((await send("/api/reservations", booking(16))).status, 401);
    const newMemberCookie = await cookie("MEMBER", member.id, activeAgain.authVersion);
    assert.equal((await send("/api/reservations", booking(16), newMemberCookie)).status, 201);
    assert.equal((await send(`/api/manage/members/${forced.id}/withdraw`, { operation: "force", requestKey: randomUUID(), expectedVersion: 1 }, staffCookie)).status, 403);
    const noMemberAccess = await fetch(`${origin}/manage/members?query=強制`, { headers: { cookie: staffCookie } });
    assert.equal(noMemberAccess.status, 200);
    assert(!(await noMemberAccess.text()).includes(forced.email));
    await db.staffPermission.create({ data: { staffId: staff.id, permission: "MEMBER_FORCE_WITHDRAW", grantedByAdminId: ADMIN_ID } });
    assert.equal((await send(`/api/manage/members/${forced.id}/withdraw`, { operation: "force", requestKey: randomUUID(), expectedVersion: 1, reviewToken: "0".repeat(64) }, staffCookie)).status, 409);
    assert.equal((await db.reservation.findUniqueOrThrow({ where: { id: forcedReservationId } })).status, "CONFIRMED");
    const forcedBody = { operation: "force", requestKey: randomUUID(), expectedVersion: 1 };
    const forcedResult = await send(`/api/manage/members/${forced.id}/withdraw`, forcedBody, staffCookie);
    assert.equal(forcedResult.status, 200, JSON.stringify(forcedResult.result));
    assert.equal(forcedResult.result.cancelledCount, 1);
    assert.equal((await db.reservation.findUniqueOrThrow({ where: { id: forcedReservationId } })).status, "CANCELLED");
    assert.equal(await db.reservationSlot.count({ where: { reservationId: forcedReservationId } }), 0);
    assert.equal((await send(`/api/manage/members/${forced.id}/withdraw`, forcedBody, staffCookie)).result.replayed, true);
    assert.equal((await db.memberLifecycleEvent.findFirstOrThrow({ where: { memberId: forced.id, kind: "FORCED_WITHDRAWAL" } })).reason, null);
    assert.equal((await send("/api/reservations", booking(17), forcedCookie)).status, 401);
    const pendingRestore = await send(`/api/manage/members/${forced.id}/restore`, { expectedVersion: 2, reason: "復旧試行" }, adminCookie);
    assert.equal(pendingRestore.status, 200, JSON.stringify(pendingRestore.result));
    const forcedDelivery = await db.emailDelivery.findFirstOrThrow({ where: { recipient: forced.email, kind: "RESTORE_CONFIRM", encryptedPayload: { not: null } }, orderBy: { createdAt: "desc" } });
    const invalidatedToken = decryptMailPayload(forcedDelivery.encryptedPayload!).text.match(/#token=([A-Za-z0-9_-]{43})/)?.[1];
    assert(invalidatedToken);
    assert.equal((await send(`/api/manage/members/${forced.id}/withdraw`, { operation: "force", requestKey: randomUUID(), expectedVersion: 3, reason: "復旧中止" }, staffCookie)).status, 200);
    assert.equal((await send("/api/member/restore", { token: invalidatedToken, password: "new-password-after-stop-123" }, "")).status, 409);
    assert.equal((await db.member.findUniqueOrThrow({ where: { id: forced.id } })).status, "WITHDRAWN");
    const pending = await db.member.create({ data: { email: "pending@example.test", emailKey: "pending@example.test", lastName: "未", firstName: "確認", lastNameKey: "未", firstNameKey: "確認", phoneNumber: "09055556666", postalCode: "0010000", ageBand: 30, passwordHash: "test-only-not-a-login-hash", status: "PENDING_EMAIL" } });
    assert.equal((await send(`/api/manage/members/${pending.id}/withdraw`, { operation: "delete", requestKey: randomUUID(), expectedVersion: 1 }, staffCookie)).status, 403);
    await db.staffPermission.create({ data: { staffId: staff.id, permission: "MEMBER_DELETE", grantedByAdminId: ADMIN_ID } });
    assert.equal((await send(`/api/manage/members/${pending.id}/withdraw`, { operation: "delete", requestKey: randomUUID(), expectedVersion: 1 }, staffCookie)).status, 200);
    assert.equal((await send(`/api/manage/members/${pending.id}/restore`, { expectedVersion: 2, reason: "復旧試行" }, adminCookie)).status, 409);
    const rollbackReservation = await send("/api/reservations", booking(9, dayAfter(8)), rollbackCookie);
    assert.equal(rollbackReservation.status, 201, JSON.stringify(rollbackReservation.result));
    const rollbackReservationId = rollbackReservation.result.reservationId as string;
    await pg.query(`CREATE FUNCTION "${schema}".reject_withdrawal_cancel() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.action = 'RESERVATION_CANCELLED_WITHDRAWAL' THEN RAISE EXCEPTION 'test rollback'; END IF; RETURN NEW; END $$`);
    await pg.query(`CREATE TRIGGER reject_withdrawal_cancel BEFORE INSERT ON "${schema}"."AuditLog" FOR EACH ROW EXECUTE FUNCTION "${schema}".reject_withdrawal_cancel()`);
    const rollbackBody = { requestKey: randomUUID(), expectedVersion: 1, reason: "ロールバック確認" };
    assert.equal((await send("/api/member/withdraw", rollbackBody, rollbackCookie)).status, 503);
    assert.equal((await db.member.findUniqueOrThrow({ where: { id: rollbackMember.id } })).status, "ACTIVE");
    assert.equal((await db.reservation.findUniqueOrThrow({ where: { id: rollbackReservationId } })).status, "CONFIRMED");
    assert.equal(await db.reservationSlot.count({ where: { reservationId: rollbackReservationId } }), 1);
    assert.equal(await db.memberLifecycleEvent.count({ where: { memberId: rollbackMember.id } }), 0);
    assert.equal(await db.appSession.count({ where: { memberId: rollbackMember.id, revokedAt: null } }), 1);
    await pg.query(`DROP TRIGGER reject_withdrawal_cancel ON "${schema}"."AuditLog"`);
    await pg.query(`DROP FUNCTION "${schema}".reject_withdrawal_cancel()`);
    assert.equal((await send("/api/member/withdraw", rollbackBody, rollbackCookie)).status, 200);
    const doubleBody = { requestKey: randomUUID(), expectedVersion: 1, reason: "二重送信" };
    const doubleResults = await Promise.all([send("/api/member/withdraw", doubleBody, doubleCookie), send("/api/member/withdraw", doubleBody, doubleCookie)]);
    assert.equal(doubleResults.filter(result => result.status === 200).length, 1, JSON.stringify(doubleResults));
    assert(doubleResults.every(result => [200, 401, 409].includes(result.status)));
    assert.equal(await db.memberLifecycleEvent.count({ where: { memberId: doubleMember.id, kind: "VOLUNTARY_WITHDRAWAL" } }), 1);
    const raceBody = { requestKey: randomUUID(), expectedVersion: 1, reason: "競合退会" };
    await pg.query("BEGIN"); await pg.query(`SET LOCAL search_path TO "${schema}"`); await pg.query('SELECT id FROM "StoreSettingState" WHERE id=1 FOR UPDATE');
    const raceBooking = send("/api/reservations", booking(9, dayAfter(9)), raceCookie);
    const raceWithdrawal = send("/api/member/withdraw", raceBody, raceCookie);
    await new Promise(done => setTimeout(done, 250));
    await pg.query("COMMIT");
    const raceResults = await Promise.all([raceBooking, raceWithdrawal]);
    assert.equal(raceResults[1].status, 200, JSON.stringify(raceResults));
    assert([201, 401, 403].includes(raceResults[0].status));
    assert.equal(await db.reservation.count({ where: { memberId: racing.id, status: "CONFIRMED" } }), 0);
    assert.equal(await db.memberLifecycleEvent.count({ where: { memberId: racing.id, kind: "VOLUNTARY_WITHDRAWAL" } }), 1);
    const memberList = await fetch(`${origin}/manage/members?query=強制`, { headers: { cookie: staffCookie } });
    assert.equal(memberList.status, 200);
    assert((await memberList.text()).includes(forced.email));
    const memberDetail = await fetch(`${origin}/manage/members/${forced.id}`, { headers: { cookie: staffCookie } });
    assert.equal(memberDetail.status, 200);
    const detailHtml = await memberDetail.text();
    assert(detailHtml.includes("論理削除済み") && detailHtml.includes("予約履歴"));
    const unauthorizedMembers = await fetch(`${origin}/manage/members`, { headers: { cookie: memberCookie }, redirect: "manual" });
    assert([302, 303, 307, 308].includes(unauthorizedMembers.status));
    const reviewListDenied = await fetch(`${origin}/manage/members/reviews`, { headers: { cookie: staffCookie } });
    assert.equal(reviewListDenied.status, 200);
    assert((await reviewListDenied.text()).includes("管理者のみ"));
    const applicant = async (suffix: string) => db!.member.create({ data: { email: `review-${suffix}@example.test`, emailKey: `review-${suffix}@example.test`, lastName: forced.lastName, firstName: forced.firstName, lastNameKey: forced.lastNameKey, firstNameKey: forced.firstNameKey, phoneNumber: "09088887777", postalCode: "0010000", ageBand: 30, passwordHash: "test-only-not-a-login-hash", status: "PENDING_REVIEW", emailVerifiedAt: new Date() } });
    const firstApplicant = await applicant("different");
    const firstReview = await db.memberReview.create({ data: { memberId: firstApplicant.id, matches: { create: { matchedMemberId: forced.id } } } });
    const reviewPage = await fetch(`${origin}/manage/members/reviews/${firstReview.id}`, { headers: { cookie: adminCookie } });
    assert.equal(reviewPage.status, 200);
    const reviewHtml = await reviewPage.text();
    assert(reviewHtml.includes(firstApplicant.email) && reviewHtml.includes(forced.email));
    const reviewInput = { requestKey: randomUUID(), expectedReviewVersion: 1, expectedMemberVersion: 1, decision: "DIFFERENT_PERSON", reason: "本人情報を照合して別人と確認" };
    assert.equal((await send(`/api/manage/members/reviews/${firstReview.id}`, reviewInput, staffCookie)).status, 403);
    assert.equal((await send(`/api/manage/members/reviews/${firstReview.id}`, { ...reviewInput, expectedMemberVersion: 2 }, adminCookie)).status, 409);
    const reviewResult = await send(`/api/manage/members/reviews/${firstReview.id}`, reviewInput, adminCookie);
    assert.equal(reviewResult.status, 200, JSON.stringify(reviewResult.result));
    assert.equal(reviewResult.result.memberStatus, "ACTIVE");
    assert.equal((await send(`/api/manage/members/reviews/${firstReview.id}`, reviewInput, adminCookie)).result.replayed, true);
    const activated = await db.member.findUniqueOrThrow({ where: { id: firstApplicant.id } });
    assert.equal(activated.status, "ACTIVE"); assert(activated.firstActivatedAt);
    assert.equal((await db.memberReview.findUniqueOrThrow({ where: { id: firstReview.id } })).decision, "DIFFERENT_PERSON");
    const secondApplicant = await applicant("same");
    const secondReview = await db.memberReview.create({ data: { memberId: secondApplicant.id, matches: { create: { matchedMemberId: forced.id } } } });
    const same = await send(`/api/manage/members/reviews/${secondReview.id}`, { requestKey: randomUUID(), expectedReviewVersion: 1, expectedMemberVersion: 1, decision: "SAME_PERSON", reason: "退会済み本人と確認" }, adminCookie);
    assert.equal(same.status, 200, JSON.stringify(same.result));
    const rejected = await db.member.findUniqueOrThrow({ where: { id: secondApplicant.id } });
    assert.equal(rejected.status, "REJECTED"); assert.equal(rejected.firstActivatedAt, null);
    assert.equal(await db.memberReviewMatch.count({ where: { reviewId: secondReview.id } }), 1);
    assert.equal(await db.member.count({ where: { id: forced.id } }), 1);
    assert.equal(await db.reservation.count({ where: { id: forcedReservationId } }), 1);
    process.stdout.write("Withdrawal, session revocation, restoration, concurrent booking and history checks passed in isolated PostgreSQL.\n");
  } finally {
    if (server) { server.kill("SIGTERM"); await once(server, "exit").catch(() => {}); }
    await db?.$disconnect();
    rmSync(distDir, { recursive: true, force: true });
    await pg.query("ROLLBACK").catch(() => {});
    await pg.query(`DROP SCHEMA IF EXISTS "${schema}" CASCADE`);
    await pg.end();
  }
}
main().catch(error => { process.stderr.write(`${error instanceof Error ? error.stack : String(error)}\n`); process.exitCode = 1; });
