import assert from "node:assert/strict";
import { randomBytes, randomUUID } from "node:crypto";
import { spawn, type ChildProcess } from "node:child_process";
import { createServer } from "node:net";
import { once } from "node:events";
import { mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { Client } from "pg";
import { PrismaPg } from "@prisma/adapter-pg";
import { PrismaClient } from "../src/generated/prisma/client";
import { loadDevelopmentDatabase, runPrisma } from "./lib/development-database";
import { seedDevelopment, seedIds } from "../prisma/seed-data";
import { tokyoBusinessDate, parseBusinessDate } from "../src/lib/schedules/calendar";
import { tokyoInstant } from "../src/lib/booking/availability-core";
import { ADMIN_ID } from "../src/lib/auth/policy";
import { encode } from "next-auth/jwt";

function dayAfter(days: number) {
  const date = new Date(parseBusinessDate(tokyoBusinessDate(new Date())).getTime() + days * 86_400_000);
  while (date.getUTCDay() === 0) date.setUTCDate(date.getUTCDate() + 1);
  return date.toISOString().slice(0, 10);
}
const iso = (date: string, hour: number) => new Date(tokyoInstant(date, hour)).toISOString();

async function main() {
  const connectionString = loadDevelopmentDatabase();
  const schema = `booking_verify_${randomUUID().replaceAll("-", "")}`;
  const pg = new Client({ connectionString });
  await pg.connect();
  const distDir = `.next-booking-test-${schema}`;
  let db: PrismaClient | undefined;
  let server: ChildProcess | undefined;
  try {
    await pg.query(`CREATE SCHEMA "${schema}"`);
    const url = new URL(connectionString); url.searchParams.set("schema", schema);
    runPrisma(["migrate", "deploy"], url.href);
    process.env.DATABASE_URL = url.href;
    db = new PrismaClient({ adapter: new PrismaPg({ connectionString }, { schema }), log: [] });
    await seedDevelopment(db);
    await db.room.update({ where: { id: seedIds.rooms[1] }, data: { isActive: false } });
    await db.therapist.update({ where: { id: seedIds.therapists[1] }, data: { isActive: false } });
    const member = await db.member.create({ data: { email: "booking@example.test", emailKey: "booking@example.test", lastName: "予約", firstName: "花子", lastNameKey: "予約", firstNameKey: "花子", phoneNumber: "09012345678", postalCode: "0010000", ageBand: 30, passwordHash: "test-only-not-a-login-hash", status: "ACTIVE", emailVerifiedAt: new Date(), firstActivatedAt: new Date() } });
    const other = await db.member.create({ data: { email: "other@example.test", emailKey: "other@example.test", lastName: "別", firstName: "会員", lastNameKey: "別", firstNameKey: "会員", phoneNumber: "09011112222", postalCode: "0010000", ageBand: 30, passwordHash: "test-only-not-a-login-hash", status: "ACTIVE", emailVerifiedAt: new Date(), firstActivatedAt: new Date() } });
    const staff = await db.staffAccount.create({ data: { email: "booking-staff@example.test", emailKey: "booking-staff@example.test", displayName: "予約担当", passwordHash: "test-only-not-a-login-hash" } });
    const portProbe = createServer(); portProbe.listen(0, "127.0.0.1"); await once(portProbe, "listening");
    const port = (portProbe.address() as { port: number }).port;
    await new Promise<void>(done => portProbe.close(() => done()));
    const origin = `http://127.0.0.1:${port}`;
    process.env.AUTH_URL = origin;
    process.env.AUTH_SECRET = randomBytes(32).toString("hex");
    process.env.AUTH_RATE_LIMIT_SECRET = randomBytes(32).toString("hex");
    process.env.ADMIN_EMAIL = "admin@example.test";
    process.env.ADMIN_PASSWORD = randomBytes(24).toString("base64url");
    process.env.ADMIN_AUTH_VERSION = "1";
    mkdirSync(distDir);
    const tsconfig = JSON.parse(readFileSync("tsconfig.json", "utf8"));
    tsconfig.include = [resolve("src/**/*.ts"), resolve("src/**/*.tsx"), resolve("next-env.d.ts")];
    tsconfig.compilerOptions.baseUrl = process.cwd();
    tsconfig.compilerOptions.paths = { "@/*": ["./src/*"] };
    writeFileSync(`${distDir}/tsconfig.json`, JSON.stringify(tsconfig));
    server = spawn(process.execPath, ["node_modules/next/dist/bin/next", "dev", "--webpack", "-p", String(port), "-H", "127.0.0.1"], { env: { ...process.env, NODE_OPTIONS: "", NEXT_DIST_DIR: distDir, AUTH_TEST_TSCONFIG: `${distDir}/tsconfig.json` }, stdio: ["ignore", "pipe", "pipe"] });
    let output = ""; server.stdout?.on("data", part => { output = (output + String(part)).slice(-8000); }); server.stderr?.on("data", part => { output = (output + String(part)).slice(-8000); });
    let ready = false;
    for (let i = 0; i < 90; i++) { try { if ((await fetch(`${origin}/api/auth/csrf`)).ok) { ready = true; break; } } catch {} if (server.exitCode !== null) break; await new Promise(done => setTimeout(done, 500)); }
    if (!ready) process.stderr.write(output.replaceAll(process.env.ADMIN_PASSWORD!, "[redacted]"));
    assert(ready, "Test server did not become ready.");
    async function cookie(role: "MEMBER" | "STAFF" | "ADMIN", principalId: string) {
      const expiresAt = new Date(Date.now() + 60 * 60_000);
      const session = await db!.appSession.create({ data: { principalType: role, ...(role === "MEMBER" ? { memberId: principalId } : role === "STAFF" ? { staffId: principalId } : { adminId: principalId }), authVersion: 1, expiresAt } });
      const token = await encode({ token: { sid: session.id, principalId, role, authVersion: 1, absoluteExpiry: expiresAt.getTime() }, secret: process.env.AUTH_SECRET!, salt: "authjs.session-token", maxAge: 3600 });
      return `authjs.session-token=${token}`;
    }
    const memberCookie = await cookie("MEMBER", member.id);
    const otherCookie = await cookie("MEMBER", other.id);
    const adminCookie = await cookie("ADMIN", ADMIN_ID);
    const staffCookie = await cookie("STAFF", staff.id);
    async function send(method: string, path: string, body: object, session = memberCookie) {
      const response = await fetch(`${origin}${path}`, { method, headers: { origin, cookie: session, "content-type": "application/json" }, body: JSON.stringify(body) });
      const result = await response.json() as Record<string, unknown>;
      return { status: response.status, result };
    }
    const date = dayAfter(7);
    const create = (hour: number, optionIds: string[] = []) => ({ requestKey: randomUUID(), date, startsAt: iso(date, hour), treatmentId: seedIds.treatments[0], optionIds, quote: { totalDurationMinutes: optionIds.length ? 70 : 60, totalPriceYen: optionIds.length ? 7000 : 6000 } });
    const availability = await fetch(`${origin}/api/availability?date=${date}&treatmentId=${seedIds.treatments[0]}`);
    assert.equal(availability.status, 200);
    assert((await availability.json() as { times: { startsAt: string }[] }).times.some(time => time.startsAt === iso(date, 9)));
    const unauthenticated = await send("POST", "/api/reservations", create(9), "");
    assert.equal(unauthenticated.status, 401, JSON.stringify({ result: unauthenticated.result, input: create(9) }));
    assert.equal((await send("POST", "/api/reservations", { ...create(9), memberId: other.id })).status, 400);
    assert.equal((await send("POST", "/api/reservations", { ...create(11), memberId: member.id }, staffCookie)).status, 403);
    await db.staffPermission.create({ data: { staffId: staff.id, permission: "RESERVATION_CREATE", grantedByAdminId: ADMIN_ID } });
    assert.equal((await send("POST", "/api/reservations", { ...create(11), memberId: member.id }, staffCookie)).status, 201);
    assert.equal((await send("POST", "/api/reservations", { ...create(9), quote: { totalDurationMinutes: 60, totalPriceYen: 1 } })).status, 409);
    const firstBody = create(9);
    const first = await send("POST", "/api/reservations", firstBody);
    assert.equal(first.status, 201, JSON.stringify(first.result));
    const firstId = first.result.reservationId as string;
    assert.equal(await db.reservationSlot.count({ where: { reservationId: firstId } }), 1);
    async function read(path: string, session = memberCookie) {
      const response = await fetch(`${origin}${path}`, { headers: { cookie: session }, redirect: "manual" });
      return { status: response.status, result: await response.json() as Record<string, unknown> };
    }
    assert.equal((await read("/api/reservations", "")).status, 401);
    assert.equal((await read(`/api/reservations/${firstId}`, "")).status, 401);
    assert.equal((await read("/api/reservations?memberId=" + member.id)).status, 400);
    const ownList = await read("/api/reservations");
    assert.equal(ownList.status, 200);
    assert((ownList.result.reservations as { id: string }[]).some(row => row.id === firstId));
    assert(!(await read("/api/reservations", otherCookie).then(row => row.result.reservations as { id: string }[])).some(row => row.id === firstId));
    assert.equal((await read(`/api/reservations/${firstId}`, otherCookie)).status, 404);
    assert.equal((await read(`/api/reservations/${randomUUID()}`)).status, 404);
    const ownDetail = await read(`/api/reservations/${firstId}`);
    assert.equal(ownDetail.status, 200);
    assert.equal((ownDetail.result.reservation as { canCancel: boolean }).canCancel, true);
    assert.equal((ownDetail.result.reservation as { memberFirstNameSnapshot: string }).memberFirstNameSnapshot, "花子");
    const ownPage = await fetch(`${origin}/account/reservations/${firstId}`, { headers: { cookie: memberCookie }, redirect: "manual" });
    assert.equal(ownPage.status, 200);
    assert((await ownPage.text()).includes("予約詳細"));
    const foreignPage = await fetch(`${origin}/account/reservations/${firstId}`, { headers: { cookie: otherCookie }, redirect: "manual" });
    assert.equal(foreignPage.status, 404);
    assert(!(await foreignPage.text()).includes("booking@example.test"));
    const anonymousPage = await fetch(`${origin}/account/reservations/${firstId}`, { redirect: "manual" });
    assert([302, 303, 307, 308].includes(anonymousPage.status));
    assert.equal(new URL(anonymousPage.headers.get("location")!, origin).pathname, "/login");
    assert.equal((await send("POST", "/api/reservations", firstBody)).result.replayed, true);
    assert.equal((await send("POST", "/api/reservations", { ...firstBody, startsAt: iso(date, 10) })).status, 409);
    const duplicateBody = create(14);
    const duplicates = await Promise.all([send("POST", "/api/reservations", duplicateBody), send("POST", "/api/reservations", duplicateBody)]);
    assert.deepEqual(duplicates.map(row => row.status), [201, 201]);
    assert.equal(duplicates[0].result.reservationId, duplicates[1].result.reservationId);
    assert.deepEqual(duplicates.map(row => row.result.replayed).sort(), [false, true]);
    assert.equal((await send("PATCH", `/api/reservations/${firstId}`, { ...create(10), expectedVersion: 1 }, otherCookie)).status, 403);
    const changeBody = { ...create(10), expectedVersion: 1 };
    const changed = await send("PATCH", `/api/reservations/${firstId}`, changeBody);
    assert.equal(changed.status, 200, JSON.stringify(changed.result));
    assert.equal((await send("PATCH", `/api/reservations/${firstId}`, changeBody)).result.replayed, true);
    assert.equal((await send("PATCH", `/api/reservations/${firstId}`, { ...changeBody, requestKey: randomUUID() })).status, 409);
    assert.deepEqual((await db.reservationSlot.findMany({ where: { reservationId: firstId } })).map(row => row.slotStartsAt.toISOString()), [iso(date, 10)]);
    assert.equal((await send("DELETE", `/api/reservations/${firstId}`, { requestKey: randomUUID(), expectedVersion: 2 }, otherCookie)).status, 403);
    const cancelBody = { requestKey: randomUUID(), expectedVersion: 2, reason: "予定変更" };
    const cancelled = await send("DELETE", `/api/reservations/${firstId}`, cancelBody);
    assert.equal(cancelled.status, 200, JSON.stringify(cancelled.result));
    assert.equal((await send("DELETE", `/api/reservations/${firstId}`, cancelBody)).result.replayed, true);
    assert.equal((await send("DELETE", `/api/reservations/${firstId}`, { requestKey: randomUUID(), expectedVersion: 2 })).status, 409);
    assert.equal((await read(`/api/reservations/${firstId}`).then(row => row.result.reservation as { canCancel: boolean })).canCancel, false);
    assert.equal(await db.reservationSlot.count({ where: { reservationId: firstId } }), 0);
    const history = await db.reservation.findUniqueOrThrow({ where: { id: firstId } });
    assert.equal(history.status, "CANCELLED"); assert.equal(history.memberFirstNameSnapshot, "花子"); assert.equal(history.treatmentPriceYenSnapshot, 6000);
    const simultaneous = await Promise.all([send("POST", "/api/reservations", create(15)), send("POST", "/api/reservations", create(15))]);
    assert.deepEqual(simultaneous.map(row => row.status).sort(), [201, 409], JSON.stringify(simultaneous));
    assert.equal(await db.reservation.count({ where: { businessDate: parseBusinessDate(date), startsAt: new Date(iso(date, 15)), status: "CONFIRMED" } }), 1);
    const before = await db.reservation.count();
    const beforeOptions = await db.reservationOption.count();
    const beforeSlots = await db.reservationSlot.count();
    const secondSlot = iso(date, 17);
    await pg.query(`CREATE FUNCTION "${schema}".reject_second_slot() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW."slotStartsAt" = '${secondSlot}'::timestamptz THEN RAISE EXCEPTION 'test rollback'; END IF; RETURN NEW; END $$`);
    await pg.query(`CREATE TRIGGER reject_second_slot BEFORE INSERT ON "${schema}"."ReservationSlot" FOR EACH ROW EXECUTE FUNCTION "${schema}".reject_second_slot()`);
    const failed = await send("POST", "/api/reservations", create(16, [seedIds.options[0]]));
    assert.equal(failed.status, 503, JSON.stringify(failed.result));
    assert.equal(await db.reservation.count(), before);
    assert.equal(await db.reservationOption.count(), beforeOptions);
    assert.equal(await db.reservationSlot.count(), beforeSlots);
    await pg.query(`DROP TRIGGER reject_second_slot ON "${schema}"."ReservationSlot"`);
    await pg.query(`DROP FUNCTION "${schema}".reject_second_slot()`);
    const simultaneousId = simultaneous.find(row => row.status === 201)!.result.reservationId as string;
    const sameReservation = await Promise.all([
      send("PATCH", `/api/reservations/${simultaneousId}`, { ...create(16), expectedVersion: 1 }),
      send("DELETE", `/api/reservations/${simultaneousId}`, { requestKey: randomUUID(), expectedVersion: 1 }),
    ]);
    assert.deepEqual(sameReservation.map(row => row.status).sort(), [200, 409], JSON.stringify(sameReservation));
    const afterRace = await db.reservation.findUniqueOrThrow({ where: { id: simultaneousId }, include: { slots: true } });
    assert.equal(afterRace.version, 2);
    assert.equal(afterRace.slots.length, afterRace.status === "CANCELLED" ? 0 : 1);
    const settingDate = dayAfter(8);
    await pg.query("BEGIN");
    await pg.query(`SET LOCAL search_path TO "${schema}"`);
    await pg.query('SELECT id FROM "StoreSettingState" WHERE id=1 FOR UPDATE');
    const settingRequest = send("POST", "/api/reservations", { ...create(9), requestKey: randomUUID(), date: settingDate, startsAt: iso(settingDate, 9) });
    await new Promise(done => setTimeout(done, 250));
    const plan = randomUUID(), audit = randomUUID(), content = randomUUID();
    await pg.query('INSERT INTO "SchedulePlan" (id,kind,"effectiveDate") VALUES ($1,$2,$3)', [plan, "BUSINESS_DATE", settingDate]);
    await pg.query('INSERT INTO "AuditLog" (id,"requestKey","actorType",action,"targetType","targetId") VALUES ($1,$2,$3,$4,$5,$6)', [audit, randomUUID(), "SYSTEM", "test.setting", "SchedulePlan", plan]);
    await pg.query('INSERT INTO "BusinessDateOverride" (id,"isOpen","closesAt") VALUES ($1,false,$2)', [content, "18:00"]);
    await pg.query('INSERT INTO "ScheduleSettingChange" (id,"planId",revision,action,"auditId",reason,"businessOverrideId") VALUES ($1,$2,1,$3,$4,$5,$6)', [randomUUID(), plan, "CREATE", audit, "test closure", content]);
    await pg.query('UPDATE "StoreSettingState" SET version=version+1 WHERE id=1');
    await pg.query("COMMIT");
    assert.equal((await settingRequest).status, 409);
    assert.equal(await db.reservation.count({ where: { businessDate: parseBusinessDate(settingDate) } }), 0);
    const resourceDate = dayAfter(9);
    await pg.query("BEGIN");
    await pg.query(`SET LOCAL search_path TO "${schema}"`);
    await pg.query('SELECT id FROM "StoreSettingState" WHERE id=1 FOR UPDATE');
    const resourceRequest = send("POST", "/api/reservations", { ...create(9), date: resourceDate, startsAt: iso(resourceDate, 9) });
    await new Promise(done => setTimeout(done, 250));
    await pg.query('UPDATE "Room" SET "isActive"=false WHERE id=$1', [seedIds.rooms[0]]);
    await pg.query('UPDATE "StoreSettingState" SET version=version+1 WHERE id=1');
    await pg.query("COMMIT");
    assert.equal((await resourceRequest).status, 409);
    await db.room.update({ where: { id: seedIds.rooms[0] }, data: { isActive: true } });
    const catalogDate = dayAfter(10);
    await pg.query("BEGIN");
    await pg.query(`SET LOCAL search_path TO "${schema}"`);
    await pg.query('SELECT id FROM "Treatment" WHERE id=$1 FOR UPDATE', [seedIds.treatments[0]]);
    const catalogRequest = send("POST", "/api/reservations", { ...create(9), date: catalogDate, startsAt: iso(catalogDate, 9) });
    await new Promise(done => setTimeout(done, 250));
    await pg.query('UPDATE "Treatment" SET "isActive"=false WHERE id=$1', [seedIds.treatments[0]]);
    await pg.query("COMMIT");
    assert.equal((await catalogRequest).status, 409);
    await db.treatment.update({ where: { id: seedIds.treatments[0] }, data: { isActive: true } });
    const withdrawalDate = dayAfter(11);
    await pg.query("BEGIN");
    await pg.query(`SET LOCAL search_path TO "${schema}"`);
    await pg.query('SELECT id FROM "Member" WHERE id=$1 FOR UPDATE', [other.id]);
    const withdrawalRequest = send("POST", "/api/reservations", { ...create(9), date: withdrawalDate, startsAt: iso(withdrawalDate, 9) }, otherCookie);
    await new Promise(done => setTimeout(done, 250));
    await pg.query('UPDATE "Member" SET status=$1,"isDeleted"=true WHERE id=$2', ["WITHDRAWN", other.id]);
    await pg.query("COMMIT");
    assert([401, 403].includes((await withdrawalRequest).status));
    assert.equal(await db.reservation.count({ where: { memberId: other.id } }), 0);
    const pastDate = new Date(parseBusinessDate(tokyoBusinessDate(new Date())).getTime() - 86_400_000).toISOString().slice(0, 10);
    const pastId = randomUUID();
    await db.reservation.create({ data: { id: pastId, memberId: member.id, treatmentId: seedIds.treatments[0], roomId: seedIds.rooms[0], therapistId: seedIds.therapists[0], memberLastNameSnapshot: member.lastName, memberFirstNameSnapshot: member.firstName, memberEmailSnapshot: member.email, memberPhoneNumberSnapshot: member.phoneNumber, treatmentNameSnapshot: "ボディケア", treatmentDurationMinutesSnapshot: 60, treatmentPriceYenSnapshot: 6000, roomNameSnapshot: "施術ルーム1", therapistNameSnapshot: "施術者1", businessDate: parseBusinessDate(pastDate), startsAt: new Date(iso(pastDate, 9)), treatmentEndsAt: new Date(iso(pastDate, 10)), occupiesUntil: new Date(iso(pastDate, 10)), totalDurationMinutes: 60, totalPriceYen: 6000, slotCount: 1 } });
    await db.reservationSlot.create({ data: { reservationId: pastId, roomId: seedIds.rooms[0], therapistId: seedIds.therapists[0], slotStartsAt: new Date(iso(pastDate, 9)) } });
    assert.equal((await read(`/api/reservations/${pastId}`).then(row => row.result.reservation as { canCancel: boolean })).canCancel, false);
    assert.equal((await send("DELETE", `/api/reservations/${pastId}`, { requestKey: randomUUID(), expectedVersion: 1 })).status, 409);
    assert.equal((await send("DELETE", `/api/reservations/${pastId}`, { requestKey: randomUUID(), expectedVersion: 1, storeException: true }, adminCookie)).status, 400);
    assert.equal((await send("DELETE", `/api/reservations/${pastId}`, { requestKey: randomUUID(), expectedVersion: 1, storeException: true, exceptionReason: "店舗都合の中止" }, adminCookie)).status, 200);
    assert.equal(await db.reservationSlot.count({ where: { reservationId: pastId } }), 0);
    const pastChangeId = randomUUID();
    await db.reservation.create({ data: { id: pastChangeId, memberId: member.id, treatmentId: seedIds.treatments[0], roomId: seedIds.rooms[0], therapistId: seedIds.therapists[0], memberLastNameSnapshot: member.lastName, memberFirstNameSnapshot: member.firstName, memberEmailSnapshot: member.email, memberPhoneNumberSnapshot: member.phoneNumber, treatmentNameSnapshot: "ボディケア", treatmentDurationMinutesSnapshot: 60, treatmentPriceYenSnapshot: 6000, roomNameSnapshot: "施術ルーム1", therapistNameSnapshot: "施術者1", businessDate: parseBusinessDate(pastDate), startsAt: new Date(iso(pastDate, 11)), treatmentEndsAt: new Date(iso(pastDate, 12)), occupiesUntil: new Date(iso(pastDate, 12)), totalDurationMinutes: 60, totalPriceYen: 6000, slotCount: 1 } });
    await db.reservationSlot.create({ data: { reservationId: pastChangeId, roomId: seedIds.rooms[0], therapistId: seedIds.therapists[0], slotStartsAt: new Date(iso(pastDate, 11)) } });
    const changeDate = dayAfter(12);
    assert.equal((await send("PATCH", `/api/reservations/${pastChangeId}`, { ...create(9), date: changeDate, startsAt: iso(changeDate, 9), expectedVersion: 1 })).status, 409);
    const exceptionChange = await send("PATCH", `/api/reservations/${pastChangeId}`, { ...create(9), date: changeDate, startsAt: iso(changeDate, 9), expectedVersion: 1, storeException: true, exceptionReason: "店舗都合の移動" }, adminCookie);
    assert.equal(exceptionChange.status, 200, JSON.stringify(exceptionChange.result));
    assert.deepEqual((await db.reservationSlot.findMany({ where: { reservationId: pastChangeId } })).map(row => row.slotStartsAt.toISOString()), [iso(changeDate, 9)]);
    process.stdout.write("Booking HTTP and isolated PostgreSQL concurrency, rollback, setting, ownership and history checks passed.\n");
  } finally {
    if (server) { server.kill("SIGTERM"); await once(server, "exit").catch(() => {}); }
    await db?.$disconnect();
    rmSync(distDir, { recursive: true, force: true });
    await pg.query("ROLLBACK").catch(() => {});
    await pg.query(`DROP SCHEMA IF EXISTS "${schema}" CASCADE`);
    await pg.end();
  }
}
main().catch(error => { process.stderr.write(`${error instanceof Error ? error.stack : String(error)}\n`); process.exitCode = 1; });
